// Fact of the Day Data
export const FOTD_FACTS=[
// === CARDIOLOGY ===
{cat:"Cardiology",topic:"ACLS: Cardiac Arrest",fact:"ETCO2 <10 mmHg in intubated patients after 20 minutes of CPR is approximately 90% sensitive for predicting no ROSC.",context:"During CPR, waveform capnography is recommended. Keep ETCO2 at least >10 mmHg, ideally >20. ETCO2 <10 mmHg after 20 minutes of CPR is ~90% sensitive for no ROSC. This can help guide prognostication and discussions about continuing vs. terminating efforts. Access should prioritize IV first, then IO if IV is not feasible. Stat labs should include ABG with K and Hgb, CBC, BMP, LFTs, lactate, type and screen, coags, fibrinogen, and cardiac enzymes."},
{cat:"Cardiology",topic:"Bradycardia",fact:"Mobitz II and complete heart block with wide QRS always require a pacing wire — even if the patient appears hemodynamically stable.",context:"In bradycardia with a pulse, always remember to consider hyperkalemia as a reversible cause. Mobitz II and complete heart block with wide QRS always require transvenous pacing even if the patient appears stable. Hold all nodal blockers and antihypertensives if applicable. Key pearl: Atropine will NOT help in the setting of complete heart block or Mobitz II — it increases the SA node rate but cannot overcome the infranodal block."},
{cat:"Cardiology",topic:"Atrial Fibrillation",fact:"DOACs are recommended over warfarin for stroke prevention in AF — except in patients with moderate-to-severe mitral stenosis, HOCM, or mechanical heart valves.",context:"Anticoagulation is recommended for all AF patients except those with CHA2DS2-VASc score of 0. DOACs (dabigatran, rivaroxaban, apixaban, edoxaban) offer reduced risk of stroke, mortality, and intracranial hemorrhage compared to warfarin. Apixaban has the lowest GI bleed risk among DOACs. For patients with CrCl <15 or on dialysis, either warfarin or apixaban may be used. Rate control with IV metoprolol is preferred in most cases of RVR."},
{cat:"Cardiology",topic:"Acute Coronary Syndrome",fact:"Type 2 MI is caused by supply-demand mismatch (not atherothrombosis) — most commonly due to sepsis, arrhythmias, severe hypertension, or anemia. Management differs significantly from Type 1 MI.",context:"Myocardial injury is defined as troponin >99th percentile without evidence of ischemia. Myocardial infarction requires troponin elevation plus rise/fall pattern with ischemic symptoms. Type 1 MI involves spontaneous plaque rupture with thrombus formation. Type 2 MI involves supply-demand mismatch. The distinction is critical because Type 2 MI management focuses on treating the underlying cause rather than antiplatelet/anticoagulation therapy."},
{cat:"Cardiology",topic:"Heart Failure",fact:"In ADHF, NIPPV (BiPAP) may improve mortality and reduce intubation. Mild-moderate creatinine increases during aggressive diuresis are often benign hemodynamic changes, not a reason to stop diuretics.",context:"ADHF management centers on diuresis. Daily weights and hemoconcentration are useful endpoints. Worsening renal function occurs in ~23% of patients treated for ADHF, but mild Cr bumps should not preclude further diuresis if the patient remains congested. Vasodilators (nitroglycerin, nitroprusside) can relieve symptoms by reducing afterload and PCWP."},
{cat:"Cardiology",topic:"Cardiac Tamponade",fact:"In cardiac tamponade, positive pressure ventilation should be avoided — increased intrathoracic pressure further impedes ventricular filling. The rate of accumulation matters more than volume.",context:"Treatment priorities: urgent fluid resuscitation (250-500cc boluses), inotropes if IVF insufficient (though benefit unclear as endogenous catecholamines are already maximal), and avoid beta-blockers. Definitive treatment is pericardial effusion removal via catheter pericardiocentesis or surgical pericardiectomy."},
// === PULMONARY / CRITICAL CARE ===
{cat:"Pulmonary",topic:"Pulmonary Embolism",fact:"Massive PE (with hemodynamic instability) requires systemic thrombolysis or catheter-directed therapy. Submassive PE (RV strain + elevated biomarkers but stable BP) warrants anticoagulation with consideration of escalation.",context:"PESI score and sPESI help risk-stratify PE patients. CT-PA is first-line imaging. D-dimer has high NPV but low specificity. For submassive PE, monitoring in an ICU setting is important given risk of deterioration. Duration of anticoagulation: provoked 3 months, unprovoked 3-6 months minimum with consideration for indefinite therapy."},
{cat:"Pulmonary",topic:"Sepsis",fact:"In septic shock, norepinephrine is the first-line vasopressor. Vasopressin should be added as a second agent before escalating norepinephrine dose. Steroids are indicated for refractory shock.",context:"Sepsis-3 definition: life-threatening organ dysfunction (SOFA ≥2) from dysregulated host response to infection. Septic shock: sepsis + vasopressors required for MAP ≥65 + lactate >2 despite adequate resuscitation. Hour-1 bundle: cultures → antibiotics → 30mL/kg crystalloid if hypotensive/lactate ≥4 → vasopressors if needed."},
{cat:"Pulmonary",topic:"ARDS",fact:"In ARDS, low tidal volume ventilation (6 mL/kg IBW) reduces mortality. Target plateau pressure <30 cmH2O. Prone positioning for >12 hours/day improves survival in moderate-severe ARDS.",context:"ARDS Berlin definition requires: acute onset within 1 week, bilateral opacities on imaging, respiratory failure not explained by heart failure/fluid overload, and PaO2/FiO2 <300 with PEEP ≥5. Mild: P/F 200-300. Moderate: 100-200. Severe: <100. Neuromuscular blockade may be considered in severe ARDS. ECMO is a rescue option."},
{cat:"Pulmonary",topic:"COPD Exacerbation",fact:"In COPD exacerbations, non-invasive ventilation (BiPAP) reduces intubation rates and mortality. Short-acting bronchodilators are first-line; systemic corticosteroids should be given for 5 days.",context:"COPD exacerbations are triggered by respiratory infections (most common), air pollution, and non-adherence. Antibiotics are indicated for increased purulence/dyspnea/sputum volume (Anthonisen criteria). Target SpO2 88-92% with supplemental O2 to avoid hypercapnia. Heliox can reduce work of breathing. Discharge planning includes smoking cessation, vaccination, and optimized inhaler therapy."},
{cat:"Pulmonary",topic:"Mechanical Ventilation",fact:"Initial ventilator settings in ARDS: FiO2 100%, tidal volume 6 mL/kg IBW, RR 18-22, PEEP 5-15 based on FiO2/PEEP table. Titrate to maintain plateau pressure <30 cmH2O.",context:"IBW calculation: Males = 50 + 2.3 × (height in inches - 60). Females = 45.5 + 2.3 × (height in inches - 60). High PEEP can improve oxygenation but increases risk of barotrauma and decreased venous return. Prone positioning improves V/Q matching and reduces mortality. Daily spontaneous breathing trials to assess readiness for extubation."},
// === GASTROENTEROLOGY ===
{cat:"Gastroenterology",topic:"Upper GI Bleeding",fact:"In upper GI bleeding, risk stratify with Glasgow-Blatchford score. High-risk patients need EGD within 12-24 hours. Start IV PPI drip for suspected peptic ulcer bleeding.",context:"Hematemesis, coffee-ground emesis, and melena suggest upper GI source. Volume resuscitation takes priority. Transfuse pRBC for Hgb <7 (or <9 in active bleeding or CAD). Octreotide + ceftriaxone + emergency EGD with banding for variceal bleeding. Balloon tamponade (Sengstaken-Blakemore) for refractory variceal bleeding. Consider TIPS if recurrent variceal bleeding."},
{cat:"Gastroenterology",topic:"Acute Liver Failure",fact:"In acute liver failure, encephalopathy + coagulopathy (INR >1.5) within 26 weeks of liver disease onset is the definition. N-acetylcysteine should be given for ALL causes, not just acetaminophen.",context:"Acetaminophen toxicity is the most common cause in the US. Other causes: viral hepatitis, ischemic hepatitis, drug-induced, Wilson's disease, autoimmune. Contact transplant team early. Avoid sedatives, nephrotoxins, hepatotoxic drugs. Monitor closely for complications: hypoglycemia, coagulopathy, cerebral edema, renal failure, infection."},
{cat:"Gastroenterology",topic:"Pancreatitis",fact:"Most pancreatitis is mild and self-limited. Aggressive early fluid resuscitation (250-500 mL/hr LR) in the first 24-48 hours improves outcomes. Routine antibiotics are NOT indicated unless infected necrosis is suspected.",context:"Ranson criteria and BISAP score help predict severity. CT abdomen is indicated if diagnosis is uncertain or no improvement after 48-72h. Necrotizing pancreatitis requires cross-sectional imaging. ERCP is indicated for pancreatitis with cholangitis or persistent CBD obstruction. Early enteral nutrition (within 24-48h) is preferred over TPN."},
{cat:"Gastroenterology",topic:"Hepatic Encephalopathy",fact:"Hepatic encephalopathy treatment includes lactulose titrated to 2-3 soft stools/day and rifaximin 550mg BID for secondary prophylaxis. Identify and treat precipitating factors first.",context:"Common precipitants: infection (SBP), GI bleeding, constipation, electrolyte abnormalities, medications (opioids, benzodiazepines), renal failure, dietary protein excess. Zinc supplementation may help. Avoid routine protein restriction — it worsens sarcopenia and outcomes. Branched-chain amino acids may be considered in severe cases."},
// === NEPHROLOGY ===
{cat:"Nephrology",topic:"Acute Kidney Injury",fact:"FENa <1% suggests pre-renal AKI or contrast nephropathy/myoglobulinuria. FENa >2% suggests intrinsic AKI (ATN). FENaUrea is more reliable in patients on diuretics.",context:"AKI classification: Pre-renal (most common), intrinsic, post-renal. Urine microscopy: muddy brown casts = ATN, RBC casts = glomerulonephritis, WBC casts = interstitial nephritis. Indications for dialysis (AEIOU): Acidosis, Electrolyte abnormality (K+), Intoxication, Overload (volume), Uremia."},
{cat:"Nephrology",topic:"Acid-Base Disorders",fact:"Winter's formula for expected PaCO2 in metabolic acidosis: 1.5 × (HCO3) + 8 ± 2. If actual PaCO2 is higher, there is a concurrent respiratory acidosis; if lower, concurrent respiratory alkalosis.",context:"Approach to acid-base: 1) pH → acidosis or alkalosis. 2) Primary disorder (CO2 or HCO3). 3) Compensation. 4) Anion gap if acidosis (AG = Na - Cl - HCO3, normal 8-12). 5) If AG elevated, calculate delta-delta to identify mixed disorder. 6) Urine lytes for non-AG metabolic acidosis (RTAM vs GI loss)."},
{cat:"Nephrology",topic:"Hyperkalemia",fact:"ECG changes in hyperkalemia progress: peaked T waves → widened QRS → sine wave → VFib/asystole. Calcium gluconate stabilizes cardiac membranes but does not lower K+.",context:"Treatment sequence: 1) Cardiac stabilization: Calcium gluconate 1g IV (or CaCl2 1g via central line). 2) Shift K+ intracellularly: Insulin 10U + D50, albuterol nebs, sodium bicarbonate if acidotic. 3) Remove K+: Kayexalate, patiromer, furosemide, dialysis. Emergent dialysis for severe hyperkalemia >6.5, ECG changes refractory to medical therapy, or severe renal failure."},
{cat:"Nephrology",topic:"Hyponatremia",fact:"Correct hyponatremia no faster than 8 mEq/L in 24 hours (10-12 mEq/L max) to prevent osmotic demyelination syndrome. Use DDAVP clamp if overcorrection occurs.",context:"SIADH: euvolemic hyponatremia with low serum osm, urine osm >100, urine Na >40. Treatment: fluid restriction ± salt tabs ± tolvaptan. Hypovolemic: NS. Hypervolemic (CHF, cirrhosis): fluid/Na restriction + diuretics. Always calculate urine osmolality and sodium before starting therapy. Severe symptoms (seizures) warrant 3% saline 1-2 mL/kg IV over 20 min."},
// === INFECTIOUS DISEASE ===
{cat:"Infectious Disease",topic:"Sepsis Management",fact:"Blood cultures must be drawn BEFORE antibiotics in sepsis. Even a 1-hour delay in antibiotics increases mortality by ~7% per hour in septic shock.",context:"Sepsis hour-1 bundle: (1) obtain blood cultures, (2) give broad-spectrum antibiotics, (3) measure lactate, (4) give 30 mL/kg crystalloid if hypotensive or lactate ≥4. Vasopressors if MAP <65 despite resuscitation. Reassess volume status frequently. Source control (drainage, removal of infected device) is essential. De-escalate antibiotics based on culture data."},
{cat:"Infectious Disease",topic:"Pneumonia",fact:"CAP severity assessment with CURB-65: Confusion, Urea >7 mmol/L, RR ≥30, BP <90/60, age ≥65. Score ≥2 warrants hospitalization; ≥3 consider ICU.",context:"Outpatient CAP: amoxicillin or doxycycline. Inpatient CAP: ceftriaxone + azithromycin or respiratory fluoroquinolone. ICU: ceftriaxone + azithromycin ± vancomycin if MRSA risk. HAP/VAP: anti-pseudomonal beta-lactam ± MRSA coverage. Aspiration: antibiotics only if clear infection, not routine prophylaxis. Legionella/pneumococcal urine antigens for severe CAP."},
{cat:"Infectious Disease",topic:"Endocarditis",fact:"Duke criteria for infective endocarditis: 2 major, 1 major + 3 minor, or 5 minor = definite IE. Blood cultures should be drawn from 3 separate sites before antibiotics.",context:"Major criteria: positive blood cultures (typical organisms in ≥2), evidence of endocardial involvement (echo or new regurgitation). Minor criteria: predisposing condition, fever >38°C, vascular phenomena, immunologic phenomena, microbiologic evidence. Indications for early surgery: heart failure, persistent bacteremia, large vegetation, abscess, or prosthetic valve."},
{cat:"Infectious Disease",topic:"C. difficile",fact:"Fidaxomicin is preferred over vancomycin for first-line treatment of C. difficile in non-severe cases — it has lower recurrence rates. Metronidazole is no longer first-line for CDI.",context:"CDI severity: Non-severe (WBC <15k, Cr <1.5 baseline), Severe (WBC ≥15k or Cr ≥1.5), Fulminant (hypotension, ileus, megacolon). Treatment: Non-severe/severe: Fidaxomicin 200mg BID x10d or vancomycin 125mg QID x10d. Fulminant: vancomycin 500mg QID PO/NG + metronidazole 500mg IV q8h. Fecal microbiota transplant for recurrent CDI."},
// === HEMATOLOGY ===
{cat:"Hematology",topic:"Anticoagulation",fact:"For urgent reversal of warfarin: 4-factor PCC (Kcentra) is preferred over FFP — faster onset, smaller volume, no thromboembolic risk from ABO mismatch. Always give vitamin K concurrently.",context:"INR reversal with 4F-PCC: dose based on INR and weight. Effect in 30 min, lasts ~6-8 hours. Vitamin K given alongside to prevent rebound. Dabigatran reversal: idarucizumab (Praxbind) 5g IV. Rivaroxaban/apixaban reversal: andexanet alfa (Andexxa) or 4F-PCC as alternative. Heparin reversal: protamine 1mg per 100 units UFH."},
{cat:"Hematology",topic:"Thrombocytopenia",fact:"HIT (heparin-induced thrombocytopenia) typically causes platelet drop 5-10 days after heparin exposure, or earlier if prior exposure. Diagnosis uses the 4T score. Stop all heparin products immediately.",context:"4T score: Thrombocytopenia (50% drop or nadir 20-100), Timing, Thrombosis, oTher cause. High probability (≥6): send HIT antibody ELISA AND functional assay (serotonin release assay). Low probability (≤3): HIT unlikely, no need for ELISA. Treatment: switch to argatroban or fondaparinux. Do NOT transfuse platelets. Warfarin can be started only after platelet recovery."},
{cat:"Hematology",topic:"Transfusion Medicine",fact:"Restrictive transfusion strategy (Hgb threshold 7 g/dL, or 8 g/dL with cardiac disease) is non-inferior to liberal strategy and reduces transfusion-related complications.",context:"One unit of pRBCs raises Hgb by approximately 1 g/dL. Fresh frozen plasma (FFP) is used for coagulopathy or factor replacement; requires ABO compatibility. Platelets transfused for counts <10k (or <50k pre-procedure, <100k with active bleeding). Cryoprecipitate contains fibrinogen, vWF, factor VIII — used for hypofibrinogenemia."},
// === ENDOCRINOLOGY ===
{cat:"Endocrinology",topic:"DKA",fact:"In DKA, do NOT give insulin until potassium is ≥3.5 mEq/L — insulin drives K+ intracellularly and can precipitate life-threatening hypokalemia. Replace K+ aggressively.",context:"DKA criteria: pH <7.3, bicarb <18, AG >12, positive ketones. Treatment: aggressive IV fluids (NS initially), insulin drip 0.1 U/kg/hr (no bolus), K+ replacement when <5.3. Transition to subQ insulin when AG closes, pH >7.3, bicarb >15, patient eating. Overlap IV and subQ by 1-2h to prevent relapse. Monitor q1-2h BMPs. HHS: glucose >600, osm >320, minimal ketosis — requires more fluid than DKA."},
{cat:"Endocrinology",topic:"Adrenal Crisis",fact:"Adrenal crisis presents with hypotension, nausea/vomiting, and abdominal pain — often in setting of physiologic stress in a patient with known/unknown adrenal insufficiency. Do NOT delay steroids for cortisol testing if clinical suspicion is high.",context:"Treatment of adrenal crisis: hydrocortisone 100mg IV bolus then 50mg q6-8h (or 200mg/24h infusion). IV fluids aggressively. Can draw cortisol/ACTH before steroid if not delaying treatment. Dexamethasone 4mg IV is an alternative if cosyntropin stimulation test planned. Sick day rules: double/triple oral steroids during illness. Patients should wear medical alert bracelet."},
{cat:"Endocrinology",topic:"Thyroid Storm",fact:"Thyroid storm is a life-threatening emergency. Treatment uses the Burch-Wartofsky scale and requires four simultaneous treatments: beta-blocker, thionamide (PTU), iodine (given AFTER PTU), and glucocorticoids.",context:"PTU is preferred over methimazole in thyroid storm because it also blocks peripheral T4→T3 conversion. Lugol's iodine or SSKI given 1 hour after PTU to block thyroid hormone release (giving before PTU can worsen storm by providing substrate). Propranolol 60-80mg q4-6h. Hydrocortisone 100mg IV q8h. Treat precipitating cause. Supportive care: cooling blankets, acetaminophen (not ASA — displaces T4 from binding proteins)."},
// === NEUROLOGY ===
{cat:"Neurology",topic:"Stroke",fact:"IV tPA can be given up to 4.5 hours from last known well in ischemic stroke. Mechanical thrombectomy can be performed up to 24 hours in selected patients with large vessel occlusion and salvageable penumbra.",context:"NIHSS guides stroke severity. Contraindications to tPA include: recent surgery/trauma, active bleeding, recent stroke, prior hemorrhagic stroke, BP >185/110, blood glucose <50 or >400. BP target: <185/110 before tPA, <180/105 after tPA. Thrombectomy (TICI 2b/3 reperfusion) significantly improves functional outcomes in LVO stroke. Antiplatelet therapy (aspirin) within 24-48h after hemorrhage exclusion."},
{cat:"Neurology",topic:"Status Epilepticus",fact:"Status epilepticus (seizure >5 minutes or ≥2 seizures without return to baseline) requires immediate benzodiazepine treatment. If two benzo doses fail, give fosphenytoin or levetiracetam. Refractory SE requires anesthesia.",context:"Treatment ladder: Lorazepam 0.1 mg/kg IV (max 4 mg) or diazepam 0.15 mg/kg IV. Repeat once if no response. Second-line: fosphenytoin 20 PE/kg IV, levetiracetam 60 mg/kg IV (max 4500 mg), or valproate 40 mg/kg. Refractory (failed 2+ antiepileptics): midazolam, propofol, or pentobarbital infusion with continuous EEG monitoring."},
{cat:"Neurology",topic:"Altered Mental Status",fact:"AMS workup: glucose is always first. Then consider AEIOU-TIPS (Alcohol/Acidosis, Epilepsy, Infection, Opiates, Uremia, Trauma, Insulin, Poisoning, Stroke/Structural/Shock).",context:"In hospitalized patients, delirium is the most common cause of AMS. CAM criteria: acute onset + fluctuating course + inattention + either disorganized thinking OR altered consciousness. Delirium risk factors: age, dementia, sensory impairment, immobility, sleep deprivation, polypharmacy. Non-pharmacologic interventions first. Avoid benzodiazepines (worsen delirium). Low-dose haloperidol or quetiapine for agitated delirium only."},
// === RHEUMATOLOGY ===
{cat:"Rheumatology",topic:"Crystal Arthropathy",fact:"In acute gout, colchicine 1.2mg then 0.6mg 1 hour later is first-line if given within 36 hours of onset. NSAIDs are equally effective. Allopurinol should NOT be started during an acute attack.",context:"Gout vs pseudogout: gout = monosodium urate crystals (negatively birefringent, needle-shaped), pseudogout = calcium pyrophosphate (positively or weakly birefringent, rhomboid-shaped). Joint aspiration is gold standard for diagnosis. Urate-lowering therapy (allopurinol, febuxostat) indicated after 2+ attacks, tophi, or uric acid nephrolithiasis. Target serum urate <6 mg/dL."},
{cat:"Rheumatology",topic:"Vasculitis",fact:"Giant cell arteritis (GCA) in patients >50 with new headache, jaw claudication, and elevated ESR/CRP requires urgent high-dose prednisone before temporal artery biopsy — do not delay for biopsy results.",context:"GCA can cause irreversible vision loss from ophthalmic artery involvement. Prednisone 40-60 mg/day. If vision loss present: IV methylprednisolone 1g/day x3 days. Temporal artery biopsy remains diagnostic gold standard but must be done within 1-2 weeks of starting steroids. Tocilizumab (IL-6 inhibitor) can be used as steroid-sparing agent. ESR typically >50 mm/hr, CRP elevated."},
// === PSYCHIATRY ===
{cat:"Psychiatry",topic:"Alcohol Withdrawal",fact:"CIWA-Ar score guides alcohol withdrawal treatment. Score ≥8-10 requires benzodiazepines. Severe withdrawal (score ≥15) or history of seizures/delirium tremens warrants ICU-level monitoring.",context:"Alcohol withdrawal timeline: 6-24h: tremor, anxiety, diaphoresis. 12-48h: withdrawal seizures (generalized tonic-clonic). 24-72h: delirium tremens (autonomic instability, hallucinations, altered sensorium). Treatment: symptom-triggered lorazepam or diazepam. Add thiamine 500mg IV TID before any dextrose. Phenobarbital for refractory cases. Consider clonidine for autonomic symptoms."},
{cat:"Psychiatry",topic:"Serotonin Syndrome",fact:"Serotonin syndrome triad: altered mental status + autonomic instability + neuromuscular abnormalities (clonus, hyperreflexia, myoclonus). Hunter criteria distinguish it from NMS. Cyproheptadine is the antidote.",context:"Most commonly caused by drug combinations (SSRIs + MAOIs, triptans, linezolid, fentanyl, tramadol, dextromethorphan). Treatment: discontinue offending agents, supportive care. Cyproheptadine 12mg then 2mg q2h PRN. Benzodiazepines for agitation. Severe: cyproheptadine + intubation/cooling. NMS (dopamine blockade) vs serotonin syndrome: NMS = lead-pipe rigidity, onset days-weeks; SS = clonus/hyperreflexia, onset hours."},
// === GI / HEPATOLOGY ===
{cat:"Gastroenterology",topic:"Spontaneous Bacterial Peritonitis",fact:"SBP is diagnosed when ascites PMN count ≥250 cells/mm³ on diagnostic paracentesis. Treat empirically with cefotaxime 2g IV q8h while awaiting cultures. Give albumin 1.5g/kg on day 1 to prevent hepatorenal syndrome.",context:"SBP prophylaxis: norfloxacin 400mg BID for prior SBP, or for high-risk patients (ascites protein <1.5 + Child-Pugh ≥9 or Cr ≥1.2 or Na ≤130). Spontaneous bacterial empyema can occur without ascites. Secondary peritonitis should be considered if multiple organisms, very high glucose, or very low LDH in ascites. Always rule out perforation with CT."},
// === PROCEDURES ===
{cat:"Procedures",topic:"Central Line",fact:"Internal jugular and subclavian central lines have similar complication rates, but subclavian has lower infection rates and IJV has lower pneumothorax risk. Femoral lines have highest infection risk.",context:"Ultrasound guidance is standard of care for central line placement and significantly reduces complications. Verify placement with CXR before use (confirm tip at SVC-RA junction, no pneumothorax). Chlorhexidine prep, full sterile drape, and daily need assessment are required. Air embolism prevention: Trendelenburg position, Valsalva during needle removal."},
{cat:"Procedures",topic:"Lumbar Puncture",fact:"Lumbar puncture should NOT be delayed for CT scan unless there are signs of increased ICP (papilledema, focal neurological deficits, altered consciousness, or known mass lesion). In bacterial meningitis, every hour of delay worsens outcomes.",context:"Normal CSF: WBC <5, protein 15-45, glucose >60 or >2/3 serum glucose, opening pressure 10-20 cmH2O. Bacterial meningitis: turbid CSF, WBC >1000 (PMN predominant), protein >100, glucose <45. Xanthochromia distinguishes SAH from traumatic tap. Give empiric antibiotics (ceftriaxone + vancomycin ± ampicillin) immediately if LP will be delayed for CT."}
];
