// Drug Reference Data
export const DRUGS_DATA={
"ICU":{
  "Vasopressors":[
    {name:"Norepinephrine (Levophed)",moa:"α1 >> β1 agonist: ↑SVR, ↑CO",dose:"Start 0.05-0.1 mcg/kg/min; titrate to MAP ≥65; max 0.75-1 mcg/kg/min",route:"Central IV (PIV <10 mcg/min short-term)",indication:"First-line vasopressor for ALL shock types",pearls:"Most studied vasopressor. Reflex bradycardia can negate chronotropy. Extravasation → phentolamine. Add vasopressin as 2nd agent before escalating NE >15 mcg/min",se:"Arrhythmias, peripheral/digital ischemia, reflex bradycardia",tags:["first-line"]},
    {name:"Vasopressin (Pitressin)",moa:"V1 receptor agonist → vasoconstriction; V2 → renal H2O reabsorption",dose:"Fixed 0.03-0.04 U/min (NOT titrated); max 0.06 U/min",route:"Central IV",indication:"Second-line septic shock (add when NE 5-15 mcg/min); catecholamine-sparing",pearls:"VASST trial: may reduce mortality in less-severe septic shock. Non-adrenergic — useful in catecholamine-resistant shock. V2 can cause hyponatremia",se:"Digital/mesenteric ischemia, hyponatremia, coronary vasoconstriction",tags:["first-line"]},
    {name:"Epinephrine (Adrenaline)",moa:"Low: β1>β2 (↑CO); High: α1>>β (↑SVR)",dose:"Low 1-4 mcg/min; High 5-35 mcg/min; Push 10-20 mcg IV; Arrest 1 mg q3-5min; Anaphylaxis 0.3-0.5 mg IM",route:"IV, IM",indication:"Cardiac arrest (1st), anaphylaxis (1st), septic shock (2nd/3rd), bradycardia",pearls:"Push dose=0.1mg diluted to 10mcg/mL. ↑Lactate via aerobic glycolysis (not worsening shock). IM 1:1000 for anaphylaxis",se:"Tachyarrhythmias, myocardial ischemia, lactic acidosis, hyperglycemia",tags:["first-line"]},
    {name:"Phenylephrine (Neo-Synephrine)",moa:"Pure α1 agonist → ↑SVR, no ↑CO",dose:"Infusion 0.5-5 mcg/kg/min; Bolus 100-200 mcg IV",route:"Central IV preferred",indication:"Hypotension w/ tachycardia; neurogenic shock; SVT w/ hypotension",pearls:"No inotropy — can ↓CO in low-output states. Causes reflex bradycardia. Avoid as sole agent in cardiogenic shock",se:"Reflex bradycardia, peripheral ischemia, ↓CO",tags:["second-line"]},
    {name:"Dopamine",moa:"Dose-dependent: Low D1 (renal); Med β1 (↑CO); High α1 (↑SVR)",dose:"2-20 mcg/kg/min",route:"Central IV",indication:"Symptomatic bradycardia w/ hypotension (if atropine fails)",pearls:"NO longer 1st-line septic shock (SOAP II: higher mortality/arrhythmia vs NE). Renal-dose dopamine is a MYTH",se:"Tachyarrhythmias (most arrhythmogenic), nausea, tissue necrosis",tags:["caution"]},
    {name:"Angiotensin II (Giapreza)",moa:"AT1 receptor agonist → vasoconstriction",dose:"Start 20 ng/kg/min; max 200 ng/kg/min",route:"Central IV",indication:"Refractory vasodilatory shock on high-dose pressors (3rd/4th line)",pearls:"ATHOS-3 trial. May benefit patients on RRT. DVT prophylaxis mandatory — thrombosis risk",se:"Thrombosis, tachycardia, delirium",tags:["second-line"]}
  ],
  "Inotropes":[
    {name:"Dobutamine",moa:"β1 > β2 → ↑CO, mild ↓SVR",dose:"2.5-20 mcg/kg/min",route:"Central IV preferred",indication:"Cardiogenic shock (with vasopressor), low-output HF, stress testing",pearls:"↑CO more than any other agent. Vasodilation may worsen hypotension (combine with NE). Tachyphylaxis in 72h. Avoid in LVOT obstruction (HOCM)",se:"Tachycardia, arrhythmias, hypotension, myocardial ischemia",tags:["first-line"]},
    {name:"Milrinone (Primacor)",moa:"PDE3 inhibitor → ↑cAMP → inotropy + vasodilation",dose:"Load 50 mcg/kg (often skipped); Infusion 0.125-0.75 mcg/kg/min",route:"IV",indication:"Cardiogenic shock, RV failure (pulmonary vasodilator), bridge to transplant/LVAD",pearls:"Pulmonary vasodilator — excellent for RV failure/pulm HTN. Renal clearance. Long t½ (2-3h). Does not ↑ myocardial O2 demand as much as dobutamine",se:"Hypotension, arrhythmias (less than dobutamine), thrombocytopenia",tags:["first-line"]}
  ],
  "Sedation":[
    {name:"Propofol",moa:"GABA-A potentiation + Na+ channel blockade",dose:"5-80 mcg/kg/min; Induction 0.5-1 mg/kg",route:"IV (dedicated line; lipid formulation)",indication:"ICU sedation 1st-line (intubated); procedural sedation; RSI",pearls:"Onset 30s. Daily SAT recommended. Check TG q48h. Count lipid calories (1.1 kcal/mL). PRIS: >70 mcg/kg/min >48h → metabolic acidosis, rhabdo, hyperK, cardiac failure",se:"Hypotension, respiratory depression, hypertriglyceridemia, PRIS, green urine",tags:["first-line"]},
    {name:"Dexmedetomidine (Precedex)",moa:"Central α2 agonist → sedation WITHOUT respiratory depression",dose:"0.2-1.5 mcg/kg/hr",route:"IV",indication:"Light sedation (RASS -1 to 0); facilitate extubation; non-intubated sedation; EtOH withdrawal adjunct; delirium",pearls:"UNIQUE: no respiratory depression. Patients arousable. Can use in non-intubated. No amnesia. Avoid in heart block/bradycardia",se:"Bradycardia, hypotension, withdrawal with abrupt stop",tags:["first-line"]},
    {name:"Midazolam (Versed)",moa:"Benzodiazepine — GABA-A modulator",dose:"Sedation 0.02-0.1 mg/kg/hr; Bolus 1-5 mg; SE: 0.2 mg/kg load",route:"IV, IM, IN",indication:"Status epilepticus (1st-line), procedural sedation; ICU sedation (LAST resort)",pearls:"PADIS: AVOID routine benzo infusion (↑delirium). Active metabolite accumulates in renal/hepatic failure. Reversal: flumazenil 0.2 mg IV",se:"Respiratory depression, delirium, paradoxical agitation, accumulation",tags:["caution"]},
    {name:"Ketamine",moa:"NMDA antagonist + opioid/monoamine activity",dose:"RSI 1-2 mg/kg; Dissociative 1-2 mg/kg; Subdissociative 0.1-0.3 mg/kg; Infusion 0.1-0.5 mg/kg/hr",route:"IV, IM",indication:"RSI (hemodynamically unstable), procedural sedation, refractory SE, bronchospasm, analgesia adjunct",pearls:"Preserves airway reflexes & respiratory drive. Sympathomimetic — maintains BP. Bronchodilator. Emergence reactions 10-20% (pretreat midazolam). Does NOT raise ICP in ventilated patients",se:"Emergence reactions, HTN, tachycardia, hypersalivation, laryngospasm (rare)",tags:["first-line"]}
  ],
  "Analgesia":[
    {name:"Fentanyl",moa:"Synthetic μ-opioid (100× morphine)",dose:"Bolus 25-100 mcg IV; Infusion 25-200 mcg/hr; Intubation 1-3 mcg/kg",route:"IV, transdermal, IN",indication:"ICU analgesia 1st-line, intubation, procedural pain",pearls:"Rapid onset 1-2min. No histamine release — preferred in hemodynamic instability. Chest wall rigidity with rapid high-dose push. Accumulates with prolonged infusion (lipophilic)",se:"Respiratory depression, chest wall rigidity, bradycardia, constipation",tags:["first-line"]},
    {name:"Hydromorphone (Dilaudid)",moa:"Semi-synthetic μ-opioid (5-7× morphine)",dose:"IV 0.2-1 mg q2-4h; PO 2-4 mg q4-6h",route:"IV, PO, SC",indication:"Moderate-severe pain; preferred in renal failure (no active metabolites)",pearls:"No active metabolites — safer in CKD than morphine. Less histamine release. 1mg IV ≈ 7mg morphine IV",se:"Respiratory depression, sedation, nausea, constipation",tags:["first-line"]},
    {name:"Morphine",moa:"μ-opioid agonist (reference standard)",dose:"IV 2-4 mg q3-4h; PO 15-30 mg q4h (IR)",route:"IV, PO, SC",indication:"Moderate-severe pain, ADHF (dyspnea), palliative care",pearls:"Active metabolite M6G accumulates in renal failure (avoid in CKD). Histamine release → hypotension/bronchospasm. Useful for dyspnea in palliative care at low doses",se:"Respiratory depression, histamine release, hypotension, constipation, pruritus",tags:["first-line"]},
    {name:"Acetaminophen (Tylenol/Ofirmev)",moa:"Central COX inhibition, serotonergic",dose:"PO/PR 650-1000 mg q6h; IV 1000 mg q6h; Max 4g/day (2g liver dz)",route:"PO, PR, IV",indication:"Multimodal analgesia adjunct; fever; opioid-sparing",pearls:"First-line adjunct in ALL pain regimens. Hepatotoxicity >4g/day (>2g in liver dz/EtOH). NAC for overdose. IV expensive — use PO/PR when possible",se:"Hepatotoxicity (overdose), rare hypotension (IV)",tags:["first-line"]}
  ],
  "Neuromuscular Blockers":[
    {name:"Rocuronium (Zemuron)",moa:"Non-depolarizing NMB (competitive nAChR antagonist)",dose:"RSI 1.2 mg/kg; Infusion 0.3-0.6 mg/kg/hr (titrate TOF 1-2/4)",route:"IV",indication:"RSI, ventilator dyssynchrony (severe ARDS), ICP management",pearls:"Onset 60-90s at RSI dose. Sugammadex reverses (16 mg/kg immediate). Preferred over sux in hyperK/burns. TOF monitoring MANDATORY for infusions. ALWAYS ensure adequate sedation before paralysis",se:"Prolonged paralysis, critical illness myopathy (prolonged use)",tags:["first-line"]},
    {name:"Cisatracurium (Nimbex)",moa:"Non-depolarizing NMB; Hofmann elimination (organ-independent)",dose:"Bolus 0.15-0.2 mg/kg; Infusion 1-3 mcg/kg/min",route:"IV",indication:"Prolonged ICU paralysis (severe ARDS), renal/hepatic failure",pearls:"Hofmann elimination — ideal for organ failure. ACURASYS trial: improved survival in severe ARDS. More predictable than rocuronium infusion",se:"Bradycardia, critical illness myopathy (prolonged)",tags:["first-line"]},
    {name:"Succinylcholine (Anectine)",moa:"Depolarizing NMB (nAChR agonist)",dose:"1-1.5 mg/kg IV; IM 3-4 mg/kg",route:"IV, IM",indication:"RSI when fastest onset needed (30-45s)",pearls:"CONTRAINDICATED: hyperK, burns >24h, crush/denervation, MH history, prolonged immobilization. ↑K+ 0.5 mEq/L. Ultra-short (5-10min). MH antidote: dantrolene 2.5 mg/kg",se:"Hyperkalemia, malignant hyperthermia, bradycardia, masseter spasm",tags:["caution"]},
    {name:"Vecuronium",moa:"Non-depolarizing NMB (intermediate duration)",dose:"Intubation 0.1 mg/kg; Infusion 0.8-1.2 mcg/kg/min",route:"IV",indication:"Alternative to rocuronium for intubation or paralysis",pearls:"Onset 2-3 min (slower than rocuronium). Duration 25-40 min. Hepatic metabolism — accumulates in liver failure. Not reversed by sugammadex as effectively as rocuronium",se:"Prolonged paralysis in hepatic failure",tags:["second-line"]}
  ],
  "Stress Ulcer & DVT Prophylaxis":[
    {name:"Pantoprazole (Protonix)",moa:"Irreversible PPI (H+/K+ ATPase)",dose:"SUP 40 mg IV/PO daily; GI bleed 80 mg bolus → 8 mg/hr × 72h",route:"IV, PO",indication:"Stress ulcer prophylaxis, GI bleed",pearls:"SUP: MV >48h, coagulopathy, GI bleed hx, TBI, burns >35%, ≥2 minor risk factors. SUP-ICU/PEPTIC: PPI ≈ H2RA. Slightly ↑C. diff",se:"C. diff, hypomagnesemia, AIN, B12 deficiency (long-term)",tags:["first-line"]},
    {name:"Famotidine (Pepcid)",moa:"H2 receptor antagonist",dose:"20 mg IV/PO q12h",route:"IV, PO",indication:"Stress ulcer prophylaxis (alternative), GERD",pearls:"Lower C. diff risk vs PPI. Tachyphylaxis in 2 weeks. May cause thrombocytopenia (prolonged use)",se:"Headache, constipation, thrombocytopenia (rare)",tags:["first-line"]},
    {name:"Enoxaparin (Lovenox)",moa:"LMWH (anti-Xa >> anti-IIa)",dose:"Ppx 40 mg SC daily (30 BID high-risk); Tx 1 mg/kg BID",route:"SC",indication:"VTE prophylaxis, VTE treatment, ACS",pearls:"AVOID CrCl <30 (use UFH). BMI>40: 40mg BID. Not easily reversible (protamine ~60%). Peak anti-Xa 4h post",se:"Bleeding, HIT (less than UFH), injection site reactions",tags:["first-line"]},
    {name:"Heparin (UFH)",moa:"AT III activator → inactivates thrombin + Xa",dose:"Ppx 5000 U SC q8-12h; Tx 80 U/kg bolus → 18 U/kg/hr",route:"IV, SC",indication:"VTE ppx/tx, ACS, PE, bridging, CrCl <30",pearls:"Short t½ (1-2h). Fully reversible (protamine 1mg/100U). Monitor aPTT. Check PLT q2-3d for HIT. Weight-based dosing essential",se:"Bleeding, HIT (1-3%), osteoporosis (long-term)",tags:["first-line"]}
  ],
  "Antiarrhythmics":[
    {name:"Amiodarone (Cordarone)",moa:"Class III (K+ blocker) + I, II, IV properties",dose:"Arrest 300mg push → 150mg; Stable 150mg/10min → 1mg/min×6h → 0.5mg/min×18h; PO load 400 TID×1wk",route:"IV, PO",indication:"VF/pVT arrest, stable VT, AF rate/rhythm control",pearls:"t½ 40-55 days. IV hypotension (diluent). Contains iodine → thyroid dysfunction. ↑Warfarin (reduce 30-50%), ↑digoxin, ↑statins. PFTs+TFTs+LFTs+eye exam baseline",se:"Pulmonary toxicity, thyroid, hepatotoxicity, corneal deposits, neuropathy, photosensitivity",tags:["first-line"]},
    {name:"Lidocaine",moa:"Class IB Na+ channel blocker",dose:"Load 1-1.5 mg/kg; repeat 0.5-0.75 q5-10min (max 3 mg/kg); Infusion 1-4 mg/min",route:"IV",indication:"VF/pVT (alternative to amio); preferred if ischemia",pearls:"Preferred over amio in active ischemia. Hepatic metabolism — reduce in CHF/liver failure. CNS toxicity: numbness → seizures → coma",se:"CNS toxicity (seizures), bradycardia, hypotension",tags:["second-line"]},
    {name:"Procainamide",moa:"Class IA Na+ + K+ channel blocker",dose:"20-50 mg/min until arrhythmia stops, QRS widens >50%, hypotension, or max 17 mg/kg",route:"IV",indication:"Stable VT, WPW w/ AF (preferred over AV nodal blockers)",pearls:"Drug of choice for WPW+AF (slows accessory pathway). Stop if QRS widens >50%. Active metabolite NAPA accumulates in renal failure",se:"Hypotension, QT prolongation, lupus-like syndrome, agranulocytosis",tags:["second-line"]},
    {name:"Adenosine",moa:"A1 receptor agonist → transient AV block",dose:"6 mg rapid push → flush; 12 mg × 1-2 if no effect; Central line HALF dose",route:"IV RAPID push with flush",indication:"SVT (AVNRT/AVRT) — diagnostic AND therapeutic",pearls:"t½ 6-10 SECONDS. Blocked by caffeine/theophylline. Potentiated by dipyridamole. Will NOT convert AF/flutter but unmasks flutter waves. Warn patient: transient chest pressure/flushing",se:"Transient chest pain, flushing, bronchospasm (avoid severe asthma), transient asystole",tags:["first-line"]},
    {name:"Sotalol",moa:"Class III (K+ blocker) + non-selective β-blocker",dose:"80-160 mg PO BID; IV 1-1.5 mg/kg over 5min",route:"PO, IV",indication:"AF rhythm control, VT prevention",pearls:"Must initiate in hospital with telemetry (QT monitoring) × 3 days. Renally cleared — dose adjust. Contraindicated if QTc >500ms, CrCl <40 (PO). Avoid with HFrEF",se:"QT prolongation/torsades, bradycardia, bronchospasm, fatigue",tags:["second-line"]},
    {name:"Dofetilide (Tikosyn)",moa:"Pure class III (IKr K+ channel blocker)",dose:"125-500 mcg PO BID (based on CrCl and QTc)",route:"PO",indication:"AF/flutter rhythm control (particularly with structural heart disease)",pearls:"MUST initiate in hospital × 3 days with telemetry and serial QTc. Multiple drug interactions. Dose based on CrCl AND QTc. Contraindicated CrCl <20. Can use with HFrEF (DIAMOND-CHF trial)",se:"QT prolongation/torsades (most significant risk), headache, dizziness",tags:["second-line"]},
    {name:"Etomidate",moa:"GABA-A agonist — sedative-hypnotic",dose:"0.3 mg/kg IV",route:"IV",indication:"RSI induction — most hemodynamically stable",pearls:"Onset 15-30s, duration 5-15min. Adrenal suppression (11β-hydroxylase) 12-24h. Myoclonus common. No analgesia. Controversial in sepsis",se:"Adrenal suppression, myoclonus, nausea",tags:["first-line"]}
  ]
},
"Cardiology":{
  "Heart Failure (GDMT)":[
    {name:"Sacubitril/Valsartan (Entresto)",moa:"Neprilysin inhibitor + ARB",dose:"Start 24/26 BID → Target 97/103 BID",route:"PO",indication:"HFrEF (EF≤40%) — replaces ACEi/ARB",pearls:"PARADIGM-HF: 20% ↓CV death/HF hosp vs enalapril. MUST washout ACEi ×36h. Follow NT-proBNP (not BNP). Part of GDMT quad: ARNI+BB+MRA+SGLT2i",se:"Hypotension, hyperkalemia, angioedema, renal impairment",tags:["first-line"]},
    {name:"Carvedilol (Coreg) / Metoprolol Succinate (Toprol-XL) / Bisoprolol",moa:"β-blockers (carvedilol: non-selective+α1; metoprolol/bisoprolol: β1-selective)",dose:"Carvedilol: 3.125→25-50 BID; Met succ: 12.5→200 daily; Bisoprolol: 1.25→10 daily",route:"PO",indication:"HFrEF (mortality benefit with these 3 only); rate control; HTN",pearls:"Only 3 BB with HFrEF mortality benefit. Start low, uptitrate q2wk. Can initiate once euvolemic. Carvedilol: more hypotension (α1). Metoprolol tartrate does NOT have HF data",se:"Hypotension, bradycardia, fatigue, bronchospasm, depression",tags:["first-line"]},
    {name:"Spironolactone (Aldactone) / Eplerenone (Inspra)",moa:"Mineralocorticoid receptor antagonists (MRA)",dose:"Spiro: 12.5-50 mg daily; Eplerenone: 25-50 mg daily",route:"PO",indication:"HFrEF (RALES/EPHESUS/EMPHASIS-HF), resistant HTN, ascites, hyperaldosteronism",pearls:"RALES: 30% mortality reduction. Monitor K+/Cr closely. CI if K>5.0 or CrCl<30. Eplerenone: selective (no gynecomastia). Spiro: anti-androgenic SEs",se:"Hyperkalemia, gynecomastia (spiro), AKI",tags:["first-line"]},
    {name:"Dapagliflozin (Farxiga) / Empagliflozin (Jardiance)",moa:"SGLT2 inhibitor → glucosuria + natriuresis",dose:"10 mg daily (both)",route:"PO",indication:"HFrEF AND HFpEF, T2DM, CKD (regardless of DM status)",pearls:"DAPA-HF/EMPEROR-Reduced/DELIVER: benefit in HFrEF and HFpEF regardless of DM. Also renoprotective (DAPA-CKD). Part of GDMT quad. Euglycemic DKA risk. Hold perioperatively",se:"Genital mycotic infections, UTI, euglycemic DKA, volume depletion",tags:["first-line"]},
    {name:"ACE Inhibitors (Lisinopril/Enalapril/Ramipril) / ARBs (Losartan/Valsartan)",moa:"ACEi: blocks ACE → ↓Ang II + ↑bradykinin; ARB: blocks AT1 receptor",dose:"Lisinopril 2.5→40 daily; Enalapril 2.5→20 BID; Losartan 25→100 daily; Valsartan 40→160 BID",route:"PO",indication:"HFrEF (if not on ARNI), HTN, CKD/proteinuria, post-MI, diabetic nephropathy",pearls:"ACEi preferred; ARB if ACEi cough. NEVER combine ACEi+ARB. Replace with ARNI when possible in HFrEF. Monitor K+/Cr 1-2wk after start/titrate. CI in bilateral RAS, angioedema hx, pregnancy",se:"Hyperkalemia, AKI, cough (ACEi 10%), angioedema (ACEi>ARB), teratogenicity",tags:["first-line"]},
    {name:"Hydralazine + Isosorbide Dinitrate (BiDil)",moa:"Arteriolar vasodilator + venodilator (NO donor)",dose:"Hydralazine 25-75 mg TID + ISDN 20-40 mg TID",route:"PO",indication:"HFrEF in Black patients (A-HeFT), or if ACEi/ARB/ARNI intolerant",pearls:"A-HeFT: 43% mortality reduction in self-identified Black patients when added to standard HF therapy. Alternative for patients intolerant to ACEi/ARB/ARNI (hyperkalemia, renal failure). TID dosing affects compliance",se:"Headache, hypotension, tachycardia, lupus-like syndrome (hydralazine), GI upset",tags:["first-line"]},
    {name:"Furosemide (Lasix) / Bumetanide (Bumex) / Torsemide",moa:"Loop diuretics — NKCC2 inhibitor (thick ascending limb)",dose:"Furosemide IV 20-200mg q6-12h, drip 5-40mg/hr; Bumetanide 1mg≈furosemide 40mg; Torsemide PO better bioavailability",route:"IV, PO",indication:"ADHF, volume overload, pulmonary edema",pearls:"IV:PO furosemide 2:1. Bumetanide 1mg=furosemide 40mg. Torsemide best PO bioavailability. Double dose if inadequate UOP in 2h. Add metolazone for resistance. Monitor K+/Mg2+ daily",se:"Hypokalemia, hypomagnesemia, metabolic alkalosis, ototoxicity (IV push), AKI",tags:["first-line"]},
    {name:"Nitroglycerin drip",moa:"NO donor → venodilation >> arteriolar dilation",dose:"Start 5-10 mcg/min; titrate q3-5min; max 200 mcg/min",route:"IV; SL 0.4mg q5min×3",indication:"ADHF with HTN, pulmonary edema, ACS",pearls:"CI: PDE5i (sildenafil 24h, tadalafil 48h), RV infarct, severe AS, HOCM. Tolerance 24-48h. Primarily ↓preload (low dose), ↓afterload (high dose)",se:"Hypotension, headache, reflex tachycardia, methemoglobinemia (rare)",tags:["first-line"]}
  ],
  "Rate Control & Antiarrhythmics":[
    {name:"Metoprolol (Lopressor/Toprol-XL)",moa:"β1-selective blocker",dose:"IV 2.5-5mg q5min (max 15mg); PO tartrate 25-100 BID; Succinate 25-200 daily",route:"IV, PO",indication:"AF/flutter rate control, ACS, HFrEF (succinate only), SVT, HTN",pearls:"Only SUCCINATE has HFrEF benefit. IV:PO ~1:2.5. Hold HR<55, SBP<90. Do not crush XL",se:"Bradycardia, hypotension, bronchospasm, fatigue, masks hypoglycemia",tags:["first-line"]},
    {name:"Diltiazem (Cardizem)",moa:"Non-DHP CCB — L-type Ca2+ blocker",dose:"IV 0.25mg/kg bolus → drip 5-15mg/hr; PO 120-360mg daily ER",route:"IV, PO",indication:"AF/flutter rate control, SVT, HTN",pearls:"IV→PO: (drip×3)+3 ≈ daily PO. Avoid HFrEF. Do NOT give IV with IV β-blocker simultaneously. Do NOT use in WPW+AF",se:"Hypotension, bradycardia, constipation, edema",tags:["first-line"]},
    {name:"Esmolol (Brevibloc)",moa:"Ultra-short β1-selective (t½ 9 min)",dose:"Load 500 mcg/kg/1min → 50-300 mcg/kg/min",route:"IV only",indication:"Acute rate control, aortic dissection, thyroid storm",pearls:"t½ 9min — ideal for testing tolerance. RBC esterase metabolism. Drug of choice for aortic dissection rate control",se:"Hypotension, bradycardia, injection site irritation",tags:["first-line"]},
    {name:"Digoxin (Lanoxin)",moa:"Na+/K+ ATPase inhibitor; vagotonic",dose:"Load 0.5mg IV → 0.25mg×2 q6h; Maint 0.125-0.25mg daily",route:"IV, PO",indication:"AF rate control (adjunct), HFrEF (symptoms, not mortality)",pearls:"Narrow index: goal 0.5-0.9 (HF). Toxicity: hypoK/hypoMg/hyperCa. Bidirectional VT=toxicity. Antidote: DigiFab",se:"Toxicity (arrhythmias, yellow vision, GI), bradycardia",tags:["second-line"]}
  ],
  "Antiplatelets":[
    {name:"Aspirin (ASA)",moa:"Irreversible COX-1 → ↓TXA2",dose:"ACS 325mg chew; Maint 81mg daily",route:"PO, PR",indication:"ACS, secondary ASCVD prevention, post-PCI",pearls:"CHEW in ACS. 81=325 for long-term (ADAPTABLE). DAPT=ASA+P2Y12i post-PCI",se:"GI bleeding, tinnitus, Reye (children)",tags:["first-line"]},
    {name:"Clopidogrel (Plavix)",moa:"Irreversible P2Y12 antagonist (prodrug — CYP2C19)",dose:"Load 300-600mg; Maint 75mg daily",route:"PO",indication:"ACS/DAPT, post-PCI, stroke/TIA, PAD",pearls:"Poor CYP2C19 metabolizers: reduced efficacy (consider ticagrelor/prasugrel). Use pantoprazole (not omeprazole). Hold 5-7d pre-surgery",se:"Bleeding, TTP (rare)",tags:["first-line"]},
    {name:"Ticagrelor (Brilinta)",moa:"Reversible P2Y12 (not prodrug — no CYP2C19 issue)",dose:"Load 180mg; Maint 90mg BID → 60mg BID after 1yr",route:"PO",indication:"ACS — superior to clopidogrel (PLATO)",pearls:"MUST use with ASA ≤100mg. Works in clopidogrel non-responders. Dyspnea 14% (adenosine-mediated). BID dosing. Reversible binding (offset 3-5d)",se:"Bleeding, dyspnea, bradycardia, hyperuricemia",tags:["first-line"]},
    {name:"Prasugrel (Effient)",moa:"Irreversible P2Y12 (more predictable prodrug)",dose:"Load 60mg; Maint 10mg daily (5mg if <60kg)",route:"PO",indication:"ACS w/ planned PCI",pearls:"CI: prior stroke/TIA, age>75 (net harm). More potent than clopidogrel. Hold 7d pre-surgery",se:"Bleeding (more than clopidogrel)",tags:["second-line"]}
  ],
  "Anticoagulation":[
    {name:"Apixaban (Eliquis)",moa:"Direct Xa inhibitor",dose:"AF 5mg BID (2.5 if ≥2: age≥80, wt≤60, Cr≥1.5); VTE 10 BID×7d → 5 BID",route:"PO",indication:"Non-valvular AF, VTE",pearls:"Lowest bleeding (ARISTOTLE). Can use in ESRD. Reversal: andexanet or 4F-PCC",se:"Bleeding, GI upset",tags:["first-line"]},
    {name:"Rivaroxaban (Xarelto)",moa:"Direct Xa inhibitor",dose:"AF 20mg daily w/ dinner; VTE 15 BID×21d → 20 daily; COMPASS 2.5 BID+ASA",route:"PO",indication:"AF, VTE, stable ASCVD/PAD (low-dose COMPASS)",pearls:"MUST take with food. Higher GI bleed than apixaban. COMPASS: 2.5mg BID+ASA in stable ASCVD/PAD",se:"Bleeding, GI upset",tags:["first-line"]},
    {name:"Warfarin (Coumadin)",moa:"Vitamin K antagonist (II,VII,IX,X + Protein C/S)",dose:"Start 5mg, adjust by INR (goal 2-3 AF/VTE; 2.5-3.5 mech valve)",route:"PO",indication:"Mechanical valves (ONLY option), mod-severe MS, APS, LVAD",pearls:"INR lags 48h. Bridge with heparin. Multiple interactions. Reversal: vit K+4F-PCC. Teratogenic",se:"Bleeding, skin necrosis, purple toe, teratogenicity",tags:["first-line"]},
    {name:"Dabigatran (Pradaxa)",moa:"Direct thrombin (IIa) inhibitor",dose:"AF 150mg BID (75 if CrCl 15-30); VTE 150 BID after 5d parenteral",route:"PO",indication:"Non-valvular AF, VTE",pearls:"80% renal clearance. Reversal: idarucizumab (Praxbind). Can be dialyzed. GI upset common (take with food)",se:"GI upset/dyspepsia, bleeding",tags:["first-line"]}
  ],
  "Lipid Management":[
    {name:"Atorvastatin (Lipitor) / Rosuvastatin (Crestor)",moa:"HMG-CoA reductase inhibitors",dose:"High-intensity: atorva 40-80mg or rosuva 20-40mg daily",route:"PO",indication:"ASCVD, post-ACS, LDL≥190, DM 40-75 w/ risk",pearls:"High-intensity for all ASCVD. Start within 24h of ACS. Rosuvastatin: most potent per mg, not CYP3A4 (fewer interactions). Atorvastatin: can give any time",se:"Myalgia (5-10%), rhabdo (rare), hepatotoxicity, new-onset DM",tags:["first-line"]},
    {name:"Ezetimibe (Zetia)",moa:"NPC1L1 inhibitor → ↓intestinal cholesterol absorption",dose:"10mg daily",route:"PO",indication:"Add-on to statin if LDL not at goal; statin intolerance",pearls:"IMPROVE-IT: ezetimibe+statin reduced CV events vs statin alone. ↓LDL ~15-20%. Well tolerated. Can combine with any statin",se:"Diarrhea, arthralgias, myalgia (rare)",tags:["first-line"]},
    {name:"PCSK9 Inhibitors (Evolocumab/Alirocumab)",moa:"Monoclonal Ab → ↑LDL receptor recycling → ↓LDL 50-60%",dose:"Evolocumab 140mg SC q2wk or 420mg monthly; Alirocumab 75-150mg SC q2wk",route:"SC injection",indication:"Familial hypercholesterolemia, ASCVD not at goal on max statin+ezetimibe",pearls:"FOURIER/ODYSSEY: reduced CV events. ↓LDL 50-60% on top of statin. Very expensive. Injectable. Consider for LDL not at goal despite maximally tolerated statin+ezetimibe",se:"Injection site reactions, nasopharyngitis, myalgia",tags:["second-line"]},
    {name:"Bempedoic Acid (Nexletol)",moa:"ACL inhibitor (same pathway as statins but upstream — no muscle effects)",dose:"180mg daily",route:"PO",indication:"Statin-intolerant patients, add-on therapy",pearls:"CLEAR Outcomes: reduced CV events in statin-intolerant. No myalgia (not active in muscle). Can combine with ezetimibe (Nexlizet). ↑Uric acid, ↑tendon rupture risk",se:"Hyperuricemia, tendon rupture, ↑Cr, UTI",tags:["second-line"]}
  ],
  "Pulmonary Hypertension":[
    {name:"PDE-5 Inhibitors (Sildenafil/Tadalafil)",moa:"↑cGMP → pulmonary vasodilation",dose:"Sildenafil 20mg TID; Tadalafil 40mg daily",route:"PO",indication:"WHO Group 1 PAH",pearls:"CI with nitrates (severe hypotension). Sildenafil also used for acute RV failure at higher doses. Tadalafil: once daily, better compliance",se:"Headache, flushing, hypotension, visual disturbances",tags:["first-line"]},
    {name:"Endothelin Receptor Antagonists (Bosentan/Ambrisentan/Macitentan)",moa:"Block ET-1 receptors → pulmonary vasodilation + anti-remodeling",dose:"Ambrisentan 5-10mg daily; Macitentan 10mg daily; Bosentan 62.5→125mg BID",route:"PO",indication:"WHO Group 1 PAH (often combined w/ PDE5i)",pearls:"Monthly LFTs with bosentan (hepatotoxic). Ambrisentan/macitentan: less hepatotoxicity. All teratogenic — mandatory pregnancy testing. AMBITION: upfront combination (ambrisentan+tadalafil) superior to monotherapy",se:"Hepatotoxicity (bosentan), edema, anemia, teratogenicity (all)",tags:["first-line"]},
    {name:"Prostacyclin Analogs (Epoprostenol/Treprostinil/Selexipag)",moa:"Prostacyclin pathway → vasodilation + antiproliferative",dose:"Epoprostenol: continuous IV; Treprostinil: SC/IV/inhaled; Selexipag: PO",route:"IV (epoprostenol), SC/IV/inhaled (treprostinil), PO (selexipag)",indication:"WHO Group 1 PAH (especially severe/IV class)",pearls:"Epoprostenol: most potent, continuous IV, t½ 3-5min (NEVER stop abruptly — rebound fatal PH crisis). Treprostinil: multiple routes. Selexipag (Uptravi): oral IP receptor agonist. GRIPHON trial for selexipag",se:"Jaw pain, flushing, headache, diarrhea, line infection (IV forms)",tags:["first-line"]},
    {name:"Riociguat (Adempas)",moa:"Soluble guanylate cyclase stimulator → ↑cGMP",dose:"Start 1mg TID → max 2.5mg TID",route:"PO",indication:"WHO Group 1 PAH, CTEPH (only approved med for CTEPH)",pearls:"ONLY drug approved for CTEPH (chronic thromboembolic PH). CI with PDE5 inhibitors and nitrates. PATENT/CHEST trials. Teratogenic",se:"Hypotension, headache, GI upset, hemoptysis",tags:["first-line"]}
  ]
},
"Pulmonary":{
  "Asthma":[
    {name:"Inhaled Corticosteroids (Fluticasone/Budesonide/Beclomethasone)",moa:"↓Airway inflammation, ↓eosinophilic infiltration",dose:"Low: fluticasone 88-250mcg BID; Med: 250-500; High: >500",route:"MDI, DPI",indication:"Persistent asthma (cornerstone of maintenance therapy)",pearls:"Rinse mouth after use (oral candidiasis). LABA should NEVER be used without ICS in asthma. ICS dose determines asthma step",se:"Oral candidiasis, dysphonia, easy bruising (high dose), adrenal suppression (rare)",tags:["first-line"]},
    {name:"LABA (Salmeterol/Formoterol) — always with ICS",moa:"Long-acting β2 agonist → bronchodilation (12h)",dose:"Usually combined: Advair (fluticasone/salmeterol), Symbicort (budesonide/formoterol)",route:"MDI, DPI",indication:"GINA Step 3+: add to ICS for persistent asthma",pearls:"NEVER use LABA alone in asthma (↑mortality without ICS — SMART trial). Formoterol has faster onset (can be used PRN in SMART therapy). Symbicort SMART=maintenance+reliever",se:"Tachycardia, tremor, hypokalemia, headache",tags:["first-line"]},
    {name:"LAMA (Tiotropium/Umeclidinium)",moa:"Long-acting muscarinic antagonist → bronchodilation (24h)",dose:"Tiotropium 2.5mcg (Respimat) daily; or 18mcg (HandiHaler)",route:"Inhaler",indication:"GINA Step 4-5: add-on to ICS-LABA; COPD maintenance 1st-line",pearls:"Added benefit in severe asthma not controlled on ICS-LABA. Primary maintenance bronchodilator in COPD. Dry mouth most common SE",se:"Dry mouth, urinary retention, constipation, glaucoma (nebulized)",tags:["first-line"]},
    {name:"Montelukast (Singulair)",moa:"Leukotriene receptor antagonist (LTRA)",dose:"10mg PO daily",route:"PO",indication:"Mild persistent asthma (alternative to ICS), exercise-induced bronchospasm, allergic rhinitis",pearls:"Less effective than ICS for asthma. FDA black box: neuropsychiatric events (depression, suicidality). Useful in aspirin-exacerbated respiratory disease (AERD/Samter triad). Step 2 alternative in mild asthma",se:"Neuropsychiatric events (black box), headache, GI upset",tags:["second-line"]},
    {name:"Asthma Biologics (Omalizumab/Mepolizumab/Dupilumab/Benralizumab/Tezepelumab)",moa:"Omalizumab: anti-IgE; Mepo/Benra: anti-IL-5; Dupilumab: anti-IL-4/13; Teze: anti-TSLP",dose:"SC injections q2-8 weeks (varies by agent)",route:"SC",indication:"Severe persistent asthma (Step 5) uncontrolled on high-dose ICS-LABA",pearls:"Omalizumab: allergic asthma (↑IgE). Mepolizumab/benralizumab: eosinophilic (blood eos ≥300). Dupilumab: eosinophilic + elevated FeNO, also for AD/CRSwNP. Tezepelumab: works regardless of phenotype. All ↓exacerbations 50%+. Very expensive",se:"Injection site reactions, anaphylaxis (omalizumab — observe 30min), eosinophilia (dupilumab), parasitic infection risk",tags:["second-line"]}
  ],
  "COPD":[
    {name:"LAMA (Tiotropium) / LABA (Salmeterol/Formoterol/Olodaterol/Vilanterol)",moa:"Bronchodilators: LAMA (24h anticholinergic) + LABA (12-24h β2)",dose:"Various inhalers; often combined (e.g., Anoro=umeclidinium/vilanterol)",route:"MDI, DPI, SMI",indication:"COPD maintenance therapy (GOLD: LAMA or LABA first-line; LAMA+LABA for Group B+)",pearls:"LAMA alone or LABA alone for initial COPD. LAMA+LABA > either alone. Triple therapy (LAMA+LABA+ICS) for frequent exacerbators w/ eos≥300. ICS NOT routine in COPD (only with elevated eos/exacerbations)",se:"Dry mouth (LAMA), tachycardia (LABA), urinary retention",tags:["first-line"]},
    {name:"Roflumilast (Daliresp)",moa:"PDE4 inhibitor → ↓inflammatory mediators",dose:"500mcg PO daily",route:"PO",indication:"Severe COPD w/ chronic bronchitis phenotype + frequent exacerbations (add-on)",pearls:"Add-on for FEV1 <50% + chronic bronchitis + frequent exacerbations despite inhalers. NOT a bronchodilator. Takes weeks for effect. GI side effects common initially (weight loss, diarrhea, nausea)",se:"Diarrhea, nausea, weight loss, headache, psychiatric (depression/suicidality)",tags:["second-line"]},
    {name:"Chronic Azithromycin",moa:"Anti-inflammatory + antimicrobial modulation",dose:"250mg PO daily or 500mg 3×/week",route:"PO",indication:"COPD with frequent exacerbations despite optimal inhaler therapy",pearls:"Albert et al (NEJM 2011): ↓exacerbations in selected COPD patients. Concern for macrolide resistance and QT prolongation. ECG before starting. Hearing test at baseline. Not for patients with resting tachycardia or QTc >450",se:"QT prolongation, hearing loss, GI upset, macrolide resistance",tags:["second-line"]}
  ],
  "Bronchodilators (Acute)":[
    {name:"Albuterol (ProAir/Proventil)",moa:"Short-acting β2 agonist (SABA)",dose:"Neb 2.5-5mg q20min×3 then q1-4h; Continuous 10-15mg/hr; MDI 4-8 puffs q20min×3",route:"Neb, MDI",indication:"Acute bronchospasm, asthma/COPD exacerbation, hyperkalemia (shifts K+)",pearls:"MDI+spacer = neb for moderate exacerbations. Continuous for severe. Also shifts K+ intracellularly. R-albuterol (levalbuterol) no proven advantage",se:"Tachycardia, tremor, hypokalemia, hyperglycemia",tags:["first-line"]},
    {name:"Ipratropium (Atrovent)",moa:"Short-acting muscarinic antagonist",dose:"Neb 0.5mg q20min×3, then q4-6h",route:"Neb, MDI",indication:"COPD exacerbation (with albuterol), severe asthma adjunct",pearls:"Always combine with albuterol acutely (DuoNeb). Onset slower (15-30min). More effective in COPD than asthma. Use mouthpiece (not mask) with glaucoma",se:"Dry mouth, urinary retention, glaucoma (nebulized mask)",tags:["first-line"]}
  ],
  "PE Treatment":[
    {name:"Thrombolytics (Alteplase for PE)",moa:"tPA → fibrinolysis → clot dissolution",dose:"Massive PE: 100mg IV over 2h (or 50mg if cardiac arrest); can give 10mg bolus then remainder",route:"IV",indication:"Massive PE (hemodynamic instability), submassive PE with clinical deterioration",pearls:"Massive PE: systemic thrombolysis or catheter-directed therapy. Half-dose (50mg) may have similar efficacy with less bleeding (MOPETT). Contraindications same as stroke tPA. Can give during CPR for suspected PE arrest. Window not as time-limited as stroke — can give days after onset",se:"Major bleeding (ICH 2-3%), minor bleeding, anaphylaxis (rare)",tags:["first-line"]}
  ]
},
"Infectious Disease":{
  "Gram-Positive Coverage":[
    {name:"Vancomycin",moa:"D-Ala-D-Ala binding → ↓cell wall synthesis",dose:"Load 25-30mg/kg; Maint 15-20mg/kg q8-12h; Target AUC/MIC 400-600; PO 125mg QID (C.diff)",route:"IV (systemic); PO (C.diff ONLY)",indication:"MRSA, empiric gram+ in severe sepsis, C.diff (PO)",pearls:"AUC-guided dosing preferred (2020 guidelines). Red man syndrome: slow infusion >1h. PO NOT absorbed systemically (C.diff ONLY). IV does NOT treat C.diff",se:"Nephrotoxicity, red man syndrome, ototoxicity, thrombocytopenia, DRESS",tags:["first-line"]},
    {name:"Linezolid (Zyvox)",moa:"Oxazolidinone — 50S ribosomal inhibitor",dose:"600mg IV/PO q12h",route:"IV, PO (100% bioavailability)",indication:"VRE, MRSA PNA (better lung penetration than vanc), osteomyelitis",pearls:"100% PO bioavailability. Weak MAOi → serotonin syndrome w/ SSRIs. Thrombocytopenia after 2wk (monitor CBC weekly). Bacteriostatic — avoid in endocarditis",se:"Thrombocytopenia, serotonin syndrome, peripheral neuropathy, lactic acidosis",tags:["second-line"]},
    {name:"Daptomycin (Cubicin)",moa:"Lipopeptide — disrupts cell membrane",dose:"Bacteremia 6mg/kg daily; Endocarditis 8-10mg/kg daily",route:"IV",indication:"MRSA/VRE bacteremia, R-sided endocarditis",pearls:"CANNOT use for PNA (inactivated by surfactant). Monitor CPK weekly. Hold statins. Bactericidal vs MRSA/VRE",se:"↑CPK/rhabdo, eosinophilic pneumonia, neuropathy",tags:["second-line"]}
  ],
  "Broad Spectrum":[
    {name:"Piperacillin-Tazobactam (Zosyn)",moa:"Extended-spectrum PCN + β-lactamase inhibitor",dose:"3.375-4.5g IV q6h (extended infusion 4h preferred)",route:"IV",indication:"Nosocomial infections, intra-abdominal, empiric broad coverage",pearls:"Extended infusion improves time >MIC. Covers gram-neg (Pseudomonas), anaerobes, gram-pos. NOT MRSA. Pip-tazo+vanc may ↑AKI (consider cefepime+vanc)",se:"Rash, diarrhea, C.diff, cytopenias, AKI (with vanc)",tags:["first-line"]},
    {name:"Cefepime (Maxipime)",moa:"4th-gen cephalosporin — anti-Pseudomonal",dose:"2g IV q8h (severe); 1-2g q8-12h (other)",route:"IV",indication:"Febrile neutropenia (1st-line), nosocomial PNA, Pseudomonal infections",pearls:"Covers Pseudomonas, most Enterobacteriaceae. NOT MRSA/anaerobes. Neurotoxicity in renal failure (encephalopathy, myoclonus). Often preferred over Zosyn when paired with vanc",se:"Neurotoxicity (renal failure), C.diff, rash",tags:["first-line"]},
    {name:"Meropenem (Merrem)",moa:"Carbapenem — broadest β-lactam",dose:"1g IV q8h (standard); 2g q8h (meningitis/CF)",route:"IV",indication:"ESBL infections, severe nosocomial, neutropenic fever (alt)",pearls:"Broadest β-lactam. NOT MRSA/VRE/Stenotrophomonas. Less seizure risk than imipenem. Reserve — overuse drives resistance",se:"Seizures (less than imipenem), C.diff, rash",tags:["second-line"]}
  ],
  "Community Pathogens":[
    {name:"Ceftriaxone (Rocephin)",moa:"3rd-gen cephalosporin",dose:"1-2g IV q24h; Meningitis 2g q12h",route:"IV, IM",indication:"CAP, UTI, SBP ppx, meningitis, gonorrhea, Lyme",pearls:"Once daily. No renal adjustment. NOT Pseudomonas. Avoid w/ calcium IV solutions. Biliary excretion",se:"Diarrhea, C.diff, biliary sludging, hemolytic anemia (rare)",tags:["first-line"]},
    {name:"Azithromycin (Zithromax)",moa:"Macrolide — 50S inhibitor",dose:"CAP 500mg d1 → 250mg d2-5; MAC ppx 1200mg weekly",route:"IV, PO",indication:"CAP (atypical coverage w/ ceftriaxone), MAC, STIs, pertussis",pearls:"Covers atypicals (Legionella, Mycoplasma, Chlamydia). QT prolongation. Long tissue t½ (68h). Increasing macrolide resistance in S. pneumo",se:"QT prolongation, GI upset, hepatotoxicity",tags:["first-line"]},
    {name:"Doxycycline",moa:"Tetracycline — 30S inhibitor",dose:"100mg PO/IV BID",route:"PO, IV",indication:"CAP (atypical), ALL tick-borne diseases (Lyme, RMSF, Ehrlichia, Anaplasma), MRSA SSTI (mild)",pearls:"Drug of choice for ALL tick-borne diseases. Good MRSA SSTI PO option. Photosensitivity. Take w/ food+water upright. No renal adjustment",se:"Photosensitivity, esophageal ulceration, GI, tooth discoloration (children)",tags:["first-line"]},
    {name:"Levofloxacin (Levaquin)",moa:"Fluoroquinolone — DNA gyrase + topoisomerase IV inhibitor",dose:"750mg daily × 5d (CAP); 500mg daily (UTI)",route:"IV, PO",indication:"CAP (respiratory FQ), complicated UTI, TB (2nd line)",pearls:"Black box: tendon rupture, neuropathy, aortic dissection, CNS. Avoid in MG. Chelated by cations. Reserve for β-lactam allergy",se:"Tendon rupture, neuropathy, QT prolongation, C.diff, aortic dissection",tags:["second-line"]}
  ],
  "Anaerobes & MRSA SSTI":[
    {name:"Metronidazole (Flagyl)",moa:"Nitroimidazole — DNA damage in anaerobes",dose:"500mg IV/PO q8h",route:"IV, PO (100% bioavailability)",indication:"Anaerobic infections, intra-abdominal, C.diff (2nd-line), brain abscess, BV",pearls:"100% PO bioavailability — switch early. Disulfiram reaction w/ alcohol. Neuropathy w/ prolonged use (>2-4wk). Now 2nd-line for C.diff",se:"Metallic taste, nausea, disulfiram reaction, neuropathy, seizures",tags:["first-line"]},
    {name:"TMP-SMX (Bactrim)",moa:"Dual folate synthesis blockade",dose:"DS 160/800 BID; PJP tx 15-20mg/kg/day (TMP) div q6-8h",route:"PO, IV",indication:"CA-MRSA SSTI (PO), UTI, PJP tx/ppx, Nocardia, Stenotrophomonas",pearls:"Drug of choice PO for CA-MRSA skin infections. PJP ppx: 1 SS or DS daily. ↑K+ (ENaC blockade). ↑SCr without true GFR decline. SJS risk",se:"Hyperkalemia, rash/SJS, marrow suppression, AKI, photosensitivity",tags:["first-line"]},
    {name:"Cefazolin (Ancef)",moa:"1st-gen cephalosporin",dose:"2g IV q8h; Surgical ppx 2g × 1",route:"IV",indication:"MSSA infections (alt to nafcillin w/ less toxicity), surgical prophylaxis",pearls:"FIRST trial: non-inferior to nafcillin for MSSA bacteremia w/ fewer SEs. Drug of choice for surgical prophylaxis",se:"Rash, diarrhea, C.diff",tags:["first-line"]}
  ],
  "Antifungals":[
    {name:"Echinocandins (Micafungin/Caspofungin/Anidulafungin)",moa:"β-D-glucan synthase inhibitors",dose:"Micafungin 100mg daily; Caspo 70mg load → 50mg daily; Anidula 200mg load → 100mg",route:"IV only",indication:"Candidemia (1st-line), invasive candidiasis, empiric antifungal in ICU",pearls:"1st-line candidemia (IDSA). Covers most Candida incl C.glabrata/C.auris. NOT Mucor, Crypto, Fusarium. Can step down to fluconazole for susceptible species",se:"Hepatotoxicity, flushing (rare), hypokalemia",tags:["first-line"]},
    {name:"Fluconazole (Diflucan)",moa:"Azole — ergosterol synthesis inhibitor",dose:"Candidemia step-down 400mg daily; Thrush 200mg→100mg; Crypto maintenance 200mg",route:"IV, PO",indication:"Candida UTI, thrush, step-down candidemia, crypto maintenance",pearls:"NOT C.glabrata/C.krusei/Aspergillus. Good CNS penetration. CYP inhibitor (↑warfarin, ↑cyclosporine). QT prolongation",se:"Hepatotoxicity, QT prolongation, drug interactions",tags:["first-line"]},
    {name:"Amphotericin B (liposomal)",moa:"Polyene — ergosterol binding → fungicidal",dose:"3-5 mg/kg IV daily",route:"IV",indication:"Mucormycosis (1st-line), invasive aspergillosis (alt), crypto meningitis (induction)",pearls:"Broadest antifungal spectrum. Pre-hydrate with NS. Drug of choice for mucormycosis. Monitor K+/Mg2+/Cr daily",se:"Nephrotoxicity, infusion reactions, hypoK, hypoMg, anemia",tags:["first-line"]}
  ],
  "Antivirals":[
    {name:"Acyclovir/Valacyclovir",moa:"Guanosine analog — viral DNA polymerase inhibitor (HSV/VZV selective)",dose:"HSV encephalitis 10mg/kg IV q8h×14-21d; Genital HSV: valacyclovir 1g BID×10d",route:"IV (acyclovir), PO (valacyclovir — better bioavailability)",indication:"HSV encephalitis, VZV, genital herpes, HSV prophylaxis",pearls:"Empiric for ANY encephalitis until HSV PCR negative. Hydrate well (crystalluria/AKI). Valacyclovir is PO prodrug (55% bioavail vs acyclovir 20%)",se:"Nephrotoxicity (crystalluria), neurotoxicity (renal failure)",tags:["first-line"]},
    {name:"Oseltamivir (Tamiflu)",moa:"Neuraminidase inhibitor → ↓influenza viral release",dose:"Treatment 75mg PO BID×5d; Prophylaxis 75mg daily×7-10d",route:"PO",indication:"Influenza treatment (within 48h onset, or any hospitalized patient), prophylaxis",pearls:"Treat ALL hospitalized influenza patients regardless of timing. Most benefit if started <48h from symptom onset but still give if hospitalized. Renal dose adjust. Baloxavir (Xofluza): single dose alternative",se:"Nausea, vomiting, headache, neuropsychiatric (rare, children)",tags:["first-line"]}
  ]
},
"Gastroenterology":{
  "Acid Suppression":[
    {name:"PPIs (Pantoprazole/Omeprazole/Esomeprazole/Lansoprazole)",moa:"Irreversible H+/K+ ATPase inhibitor",dose:"Standard 40mg daily; GI bleed 80mg bolus → 8mg/hr × 72h",route:"IV, PO",indication:"GERD, PUD, GI bleed, stress ulcer ppx, ZES, H.pylori regimens",pearls:"Long-term risks: C.diff, hypoMg, B12 deficiency, bone fracture, CKD, SBP risk in cirrhosis. Rebound on discontinuation (taper). Omeprazole inhibits CYP2C19 (↓clopidogrel — use pantoprazole instead)",se:"C.diff, hypoMg, AIN, B12 deficiency, bone fracture (long-term)",tags:["first-line"]},
    {name:"H2 Blockers (Famotidine/Ranitidine — discontinued)",moa:"H2 receptor antagonist",dose:"Famotidine 20mg IV/PO q12h",route:"IV, PO",indication:"GERD (mild), stress ulcer ppx (alt to PPI)",pearls:"Lower C.diff risk vs PPI. Tachyphylaxis in 2wk. Ranitidine withdrawn (NDMA). Famotidine is current H2RA of choice",se:"Headache, constipation, thrombocytopenia (rare)",tags:["first-line"]}
  ],
  "IBD Medications":[
    {name:"5-ASA (Mesalamine — Asacol/Lialda/Pentasa)",moa:"Topical GI anti-inflammatory",dose:"2.4-4.8g/day PO; Rectal suppository/enema nightly",route:"PO, rectal",indication:"Mild-moderate UC induction + maintenance; mild Crohn colitis",pearls:"1st-line mild-moderate UC. Topical (rectal) > oral for distal UC. Combo PO+rectal most effective for left-sided UC. Monitor renal function annually. Less effective in Crohn",se:"Headache, nausea, interstitial nephritis (rare), pancreatitis (rare)",tags:["first-line"]},
    {name:"Thiopurines (Azathioprine/6-Mercaptopurine)",moa:"Purine synthesis inhibitors → immunomodulation",dose:"AZA 2-2.5mg/kg daily; 6-MP 1-1.5mg/kg daily",route:"PO",indication:"IBD maintenance (steroid-sparing), autoimmune hepatitis",pearls:"Check TPMT/NUDT15 before starting (toxicity risk). AVOID allopurinol (↑6-MP levels → fatal myelosuppression). Monitor CBC+LFTs q12wk. Onset 8-12wk. ↑Lymphoma risk (small)",se:"Myelosuppression, hepatotoxicity, pancreatitis, infections, lymphoma",tags:["second-line"]},
    {name:"Anti-TNF Biologics (Infliximab/Adalimumab)",moa:"TNF-α inhibitors → ↓inflammation",dose:"Infliximab 5mg/kg IV at 0/2/6wk → q8wk; Adalimumab 160→80→40mg SC q2wk",route:"IV (infliximab), SC (adalimumab)",indication:"Moderate-severe UC/Crohn (induction + maintenance), RA, SpA, psoriasis",pearls:"Test for TB (quantiferon) and HBV before starting. Check drug levels + anti-drug antibodies if loss of response. Infliximab infusion reactions — premedicate. ↑Infection risk. Avoid live vaccines",se:"Infections (TB reactivation), infusion reactions, hepatotoxicity, demyelination (rare), HF worsening",tags:["first-line"]},
    {name:"Anti-Integrin (Vedolizumab) / Anti-IL-12/23 (Ustekinumab)",moa:"Vedolizumab: α4β7 integrin blocker (gut-selective); Ustekinumab: IL-12/23 inhibitor",dose:"Vedolizumab 300mg IV at 0/2/6wk → q8wk; Ustekinumab weight-based IV load → 90mg SC q8wk",route:"IV → SC",indication:"Moderate-severe IBD, especially anti-TNF failure",pearls:"Vedolizumab: gut-selective (lower systemic infection risk). Ustekinumab: effective for Crohn, recently approved for UC. Both options after anti-TNF failure. Slower onset than anti-TNF",se:"Infections (lower with vedolizumab), headache, nasopharyngitis",tags:["first-line"]}
  ],
  "Hepatic Encephalopathy":[
    {name:"Lactulose",moa:"Osmotic laxative + colonic acidification → NH4+ trapping",dose:"30mL q1-2h until BM → titrate to 2-3 BMs/day; Enema 300mL in 700mL H2O",route:"PO, rectal",indication:"Hepatic encephalopathy (acute + prevention)",pearls:"Titrate to 2-3 soft stools daily. Rectal enema if NPO. Combined with rifaximin for secondary ppx",se:"Bloating, diarrhea, dehydration, electrolyte disturbances",tags:["first-line"]},
    {name:"Rifaximin (Xifaxan)",moa:"Non-absorbable rifamycin",dose:"550mg PO BID",route:"PO",indication:"HE secondary prophylaxis (with lactulose)",pearls:"↓HE recurrence 50%. Minimal systemic absorption. NOT monotherapy for acute HE",se:"Peripheral edema, nausea",tags:["first-line"]}
  ],
  "Portal HTN & Varices":[
    {name:"Non-selective Beta Blockers (Nadolol/Propranolol/Carvedilol)",moa:"β1+β2 blockade → ↓CO + splanchnic vasoconstriction → ↓portal pressure",dose:"Nadolol 20-40→160mg daily; Propranolol 20→160mg BID; Carvedilol 6.25→12.5mg daily",route:"PO",indication:"Variceal bleed prophylaxis (primary + secondary), portal HTN",pearls:"Titrate to HR 55-60. PREDESCI trial: carvedilol may be superior. Baveno VII: carvedilol emerging 1st-line for CSPH. Discontinue if SBP<90, Na<120, AKI, SBP, refractory ascites",se:"Hypotension, bradycardia, fatigue, bronchospasm, masks hypoglycemia",tags:["first-line"]},
    {name:"Octreotide",moa:"Somatostatin analog → splanchnic vasoconstriction",dose:"50mcg IV bolus → 50mcg/hr × 3-5d",route:"IV",indication:"Acute variceal hemorrhage, hepatorenal syndrome adjunct",pearls:"Start immediately when variceal bleed suspected. Continue 3-5d post-EGD. MUST give with ceftriaxone 1g daily",se:"Hyperglycemia, bradycardia, QT prolongation",tags:["first-line"]}
  ],
  "Motility & Nausea":[
    {name:"Ondansetron (Zofran)",moa:"5-HT3 antagonist",dose:"4-8mg IV/PO q6-8h; max 16mg/day IV",route:"IV, PO, ODT",indication:"N/V (postop, chemo, gastroenteritis)",pearls:"1st-line hospital antiemetic. QT risk — avoid long QT. Constipation common. Can mask bowel obstruction",se:"QT prolongation, constipation, headache",tags:["first-line"]},
    {name:"Metoclopramide (Reglan)",moa:"D2 antagonist + 5-HT4 → prokinetic + antiemetic",dose:"10mg IV/PO q6h (max 12wk)",route:"IV, PO",indication:"Gastroparesis, antiemetic, GERD adjunct",pearls:"Black box: tardive dyskinesia >12wk. Acute dystonia (tx: diphenhydramine). Prokinetic useful in gastroparesis. Avoid in obstruction/Parkinson",se:"Tardive dyskinesia (black box), dystonia, akathisia, prolactin elevation",tags:["second-line"]},
    {name:"Promethazine (Phenergan)",moa:"H1 antagonist + D2 antagonist",dose:"12.5-25mg IV/PO/PR q4-6h",route:"IV, PO, PR, IM",indication:"N/V, motion sickness, allergic reactions (adjunct)",pearls:"Very sedating. Tissue necrosis risk with IV extravasation or intra-arterial injection — give diluted through running IV. Less QT risk than ondansetron",se:"Sedation, tissue necrosis (IV), anticholinergic effects, respiratory depression",tags:["second-line"]}
  ],
  "Hepatitis Treatment":[
    {name:"Direct-Acting Antivirals for HCV (Sofosbuvir-based regimens)",moa:"NS5B polymerase inhibitor (sofosbuvir) ± NS5A/NS3 protease inhibitors",dose:"Varies: Epclusa (sof/velpatasvir) 1 tab daily × 12wk; Mavyret (glecaprevir/pibrentasvir) 3 tabs daily × 8-12wk",route:"PO",indication:"Chronic hepatitis C (all genotypes — pangenotypic regimens available)",pearls:"SVR (cure) rates >95% for most patients. Epclusa: pangenotypic, 12wk. Mavyret: pangenotypic, 8wk (treatment-naive, non-cirrhotic). Check HBV status (risk of reactivation with HCV treatment). Check for drug interactions. Decompensated cirrhosis: sofosbuvir-based (avoid protease inhibitors)",se:"Headache, fatigue, nausea (generally well-tolerated), HBV reactivation",tags:["first-line"]}
  ]
},
"Nephrology":{
  "Volume Management":[
    {name:"Loop Diuretics (Furosemide/Bumetanide/Torsemide)",moa:"NKCC2 inhibitor (thick ascending limb)",dose:"See Cardiology HF section for dosing",route:"IV, PO",indication:"Volume overload, ADHF, CKD-associated edema, ascites",pearls:"See HF GDMT section. Bumetanide 1mg=furosemide 40mg. Torsemide: best PO bioavail, longest acting",se:"HypoK, hypoMg, metabolic alkalosis, ototoxicity, AKI",tags:["first-line"]},
    {name:"Metolazone (Zaroxolyn)",moa:"Thiazide-like (DCT NaCl cotransporter)",dose:"2.5-10mg PO, 30min BEFORE loop diuretic",route:"PO",indication:"Diuretic resistance (sequential nephron blockade)",pearls:"Give 30min before loop. Very potent — start 2.5mg. Effective even at low GFR. Monitor lytes BID. Use max 2-3 days",se:"Severe hypoK/hypoNa/hypoMg, massive diuresis",tags:["first-line"]},
    {name:"Potassium-Sparing Diuretics (Amiloride/Triamterene)",moa:"ENaC blockers (collecting duct)",dose:"Amiloride 5-10mg daily",route:"PO",indication:"Hypokalemia prevention (with thiazide/loop), Liddle syndrome, lithium-induced DI (amiloride)",pearls:"Weak diuretic alone — mainly to prevent K+ loss. Amiloride blocks ENaC (useful in Liddle). Also blocks lithium entry via ENaC → treats lithium-induced NDI. CI with K-sparing + ACEi/ARB (hyperK risk)",se:"Hyperkalemia, GI upset",tags:["second-line"]}
  ],
  "CKD Management":[
    {name:"Phosphate Binders (Sevelamer/Calcium Acetate/Lanthanum)",moa:"Bind dietary phosphate in GI tract → ↓absorption",dose:"Sevelamer 800mg TID w/ meals; Ca acetate 667mg TID w/ meals",route:"PO (with meals)",indication:"Hyperphosphatemia in CKD/ESRD",pearls:"Sevelamer preferred (no calcium load, ↓vascular calcification). Calcium-based binders: avoid if hypercalcemia or adynamic bone disease. Take WITH meals (bind dietary phosphate). Target phos 3.5-5.5",se:"GI upset, constipation (sevelamer), hypercalcemia (calcium-based)",tags:["first-line"]},
    {name:"Erythropoiesis-Stimulating Agents (Epoetin/Darbepoetin)",moa:"Recombinant EPO → stimulates RBC production",dose:"Epoetin 50-300 U/kg SC 3×/wk; Darbepoetin 0.45mcg/kg SC q1-2wk",route:"SC, IV",indication:"Anemia of CKD (Hgb <10, after iron repletion), chemo-induced anemia",pearls:"DO NOT target Hgb >11 (↑CV events — TREAT, CHOIR trials). Replete iron FIRST (TSAT >20%, ferritin >100). Darbepoetin: longer acting (weekly-biweekly). Black box in cancer: ↑tumor progression",se:"HTN, thrombosis, pure red cell aplasia (rare), ↑tumor progression (cancer)",tags:["first-line"]},
    {name:"Calcitriol / Vitamin D analogs (Paricalcitol)",moa:"Active vitamin D → ↑Ca absorption, ↓PTH",dose:"Calcitriol 0.25-0.5mcg daily; Paricalcitol 1-4mcg daily",route:"PO, IV",indication:"Secondary hyperparathyroidism in CKD/ESRD, hypocalcemia",pearls:"Calcitriol: active form (1,25-OH vitamin D). CKD patients cannot convert 25-OH → 1,25-OH. Paricalcitol: selective VDR activator (less hypercalcemia). Cinacalcet (calcimimetic) for refractory secondary hyperPTH",se:"Hypercalcemia, hyperphosphatemia",tags:["first-line"]}
  ],
  "Electrolyte Management":[
    {name:"KCl / Calcium Gluconate / MgSO4 / NaHCO3",moa:"Various electrolyte replacements — see ICU section for hyperK management",dose:"See ICU section for detailed dosing",route:"IV, PO",indication:"Electrolyte corrections",pearls:"K: always check Mg first. Ca gluconate: membrane stabilizer in hyperK (does NOT lower K). MgSO4: 1st-line torsades. NaHCO3: TCA OD, severe acidosis. See ICU section for comprehensive details",se:"See ICU section",tags:["first-line"]},
    {name:"Sodium Polystyrene Sulfonate (Kayexalate) / Patiromer (Veltassa) / SZC (Lokelma)",moa:"K+ binders: exchange K+ for Na+ (kayexalate), Ca2+ (patiromer), or H+/Na+ (SZC)",dose:"Kayexalate 15-30g PO; Patiromer 8.4g daily; SZC 10g TID×48h → 5-10g daily",route:"PO",indication:"Chronic/subacute hyperkalemia management",pearls:"Kayexalate: slow onset (hours), GI necrosis risk (especially with sorbitol). Patiromer/SZC: newer, safer, faster. SZC works within 1h. Patiromer cannot be given within 3h of other PO meds. NONE are for acute life-threatening hyperK (use Ca gluconate + insulin/D50)",se:"GI upset; Kayexalate: intestinal necrosis (rare but serious); Patiromer: hypoMg; SZC: edema",tags:["first-line"]}
  ]
},
"Endocrinology":{
  "Diabetes":[
    {name:"Metformin (Glucophage)",moa:"↓Hepatic glucose production, ↑insulin sensitivity (AMPK)",dose:"Start 500mg daily → target 1000mg BID",route:"PO",indication:"T2DM first-line, PCOS, prediabetes",pearls:"1st-line T2DM. Weight-neutral. No hypoglycemia as monotherapy. CI GFR<30, hold GFR 30-45 during illness. Hold 48h around contrast if GFR<60. GI SEs improve with food/slow titration. B12 deficiency long-term",se:"GI upset, B12 deficiency, lactic acidosis (rare, renal failure)",tags:["first-line"]},
    {name:"GLP-1 Receptor Agonists (Semaglutide/Liraglutide/Dulaglutide/Tirzepatide)",moa:"GLP-1 (± GIP for tirzepatide) → ↑insulin, ↓glucagon, ↓gastric emptying, ↓appetite",dose:"Semaglutide 0.25→0.5→1mg SC weekly (or PO 3→7→14mg); Tirzepatide 2.5→5→10→15mg SC weekly",route:"SC (most), PO (semaglutide)",indication:"T2DM (especially with ASCVD, HF, CKD, or obesity), obesity/weight management",pearls:"CV benefit: semaglutide (SUSTAIN-6, SELECT), liraglutide (LEADER), dulaglutide (REWIND). Tirzepatide: dual GIP/GLP-1, most potent A1c + weight reduction. Weight loss 10-20%. Use before insulin if possible. Avoid w/ hx of medullary thyroid CA or MEN2 (black box in rodent studies)",se:"Nausea/vomiting (dose-dependent, improves), pancreatitis (rare), gallstones, thyroid C-cell tumors (rodent, theoretical)",tags:["first-line"]},
    {name:"Sulfonylureas (Glipizide/Glyburide/Glimepiride)",moa:"Close K-ATP channels on β-cells → ↑insulin secretion",dose:"Glipizide 5-20mg daily; Glimepiride 1-4mg daily",route:"PO",indication:"T2DM (less preferred due to hypoglycemia/weight gain, but inexpensive)",pearls:"Cheap and effective. Cause HYPOGLYCEMIA (especially glyburide — avoid in elderly/CKD). Weight gain. Glipizide preferred in CKD (shorter acting). Less preferred vs GLP-1/SGLT2i given CV neutral",se:"Hypoglycemia, weight gain",tags:["second-line"]},
    {name:"DPP-4 Inhibitors (Sitagliptin/Linagliptin/Saxagliptin)",moa:"↓DPP-4 degradation of GLP-1/GIP → modest ↑insulin",dose:"Sitagliptin 100mg daily (50 if CrCl 30-50; 25 if <30); Linagliptin 5mg (no renal adjustment)",route:"PO",indication:"T2DM (well-tolerated, weight-neutral, less potent than GLP-1RA)",pearls:"Weight-neutral, no hypoglycemia. CV neutral (TECOS for sitagliptin). Linagliptin: no renal adjustment. Less A1c reduction than GLP-1RA or SGLT2i. Saxagliptin: ↑HF hospitalization (SAVOR-TIMI — avoid in HF)",se:"Nasopharyngitis, headache, pancreatitis (rare), HF (saxagliptin)",tags:["second-line"]},
    {name:"Insulin (Basal/Bolus/Mixed)",moa:"Exogenous insulin replacement",dose:"Basal: glargine 0.2-0.4 U/kg; Hospital: TDD 0.3-0.5 U/kg (50% basal, 50% bolus)",route:"SC",indication:"T1DM (always), T2DM (if A1c very high, failing orals, DKA/HHS)",pearls:"See ICU section for DKA management. NEVER hold basal in NPO (reduce 20-50%). Overlap IV→SC by 1-2h. Hospital basal-bolus regimen. Sliding scale alone is INADEQUATE for most inpatients",se:"Hypoglycemia, weight gain, lipodystrophy",tags:["first-line"]}
  ],
  "Thyroid":[
    {name:"Levothyroxine / Methimazole / PTU",moa:"See detailed entries in ICU section",dose:"See detailed entries",route:"PO",indication:"Hypothyroidism / Hyperthyroidism / Thyroid storm",pearls:"Levothyroxine: empty stomach 30-60min before food. Methimazole: 1st-line hyperthyroid. PTU: 1st-line thyroid storm (blocks T4→T3). See ICU section for details",se:"See detailed entries",tags:["first-line"]}
  ],
  "Adrenal & Steroids":[
    {name:"Hydrocortisone / Dexamethasone / Fludrocortisone",moa:"Glucocorticoids ± mineralocorticoid",dose:"See ICU section for crisis/stress dosing",route:"IV, PO",indication:"Adrenal insufficiency, septic shock, various inflammatory conditions",pearls:"Fludrocortisone: mineralocorticoid for primary adrenal insufficiency (0.05-0.2mg daily). Ketoconazole/metyrapone: inhibit cortisol synthesis (Cushing treatment). See ICU section for crisis management",se:"Hyperglycemia, immunosuppression, osteoporosis, adrenal suppression",tags:["first-line"]}
  ],
  "Osteoporosis":[
    {name:"Bisphosphonates (Alendronate/Risedronate/Zoledronic acid)",moa:"Inhibit osteoclast activity → ↓bone resorption",dose:"Alendronate 70mg PO weekly; Zoledronic acid 5mg IV yearly",route:"PO (weekly), IV (yearly)",indication:"Osteoporosis treatment + prevention",pearls:"PO: take upright with water, 30min before food (esophageal irritation). IV zoledronic acid: once yearly (best compliance). Osteonecrosis of jaw (rare — dental exam before starting). Atypical femur fracture (>5yr use). Drug holiday after 3-5yr for low-risk patients",se:"Esophageal irritation (PO), flu-like symptoms (IV), osteonecrosis of jaw, atypical fractures",tags:["first-line"]},
    {name:"Denosumab (Prolia)",moa:"RANKL inhibitor → ↓osteoclast formation",dose:"60mg SC q6 months",route:"SC",indication:"Osteoporosis (especially if bisphosphonate-intolerant or CKD stage 4-5)",pearls:"Good option in CKD (not renally cleared). MUST NOT stop abruptly — rebound vertebral fractures on discontinuation (transition to bisphosphonate). Monitor Ca (hypocalcemia). Q6 month dosing",se:"Hypocalcemia, skin infections, ONJ, atypical fractures, rebound fractures on stopping",tags:["first-line"]},
    {name:"Teriparatide (Forteo) / Abaloparatide",moa:"PTH analog → ↑osteoblast activity (anabolic)",dose:"Teriparatide 20mcg SC daily × 2yr max",route:"SC daily",indication:"Severe osteoporosis, multiple fractures, failed bisphosphonates",pearls:"ANABOLIC (builds bone) vs antiresorptive. Max 2yr (osteosarcoma in rodent studies). Must follow with bisphosphonate/denosumab to maintain gains. Most potent for fracture risk reduction. Very expensive",se:"Hypercalcemia, orthostatic hypotension, leg cramps, osteosarcoma (theoretical, rodent)",tags:["second-line"]}
  ]
},
"Neurology":{
  "Seizures":[
    {name:"Levetiracetam (Keppra)",moa:"SV2A modulator",dose:"Load 60mg/kg (max 4500mg); Maint 500-1500mg BID",route:"IV, PO",indication:"SE (2nd-line), seizure ppx, focal/generalized epilepsy",pearls:"No hepatic metabolism — minimal interactions. Renal dosing. Most common maintenance AED in hospital. Keppra rage (5-10%). Well tolerated overall",se:"Behavioral changes, somnolence, dizziness",tags:["first-line"]},
    {name:"Valproic Acid (Depakote)",moa:"GABA potentiation + Na+/Ca2+ channel blockade",dose:"SE 40mg/kg IV; Maint 500-1000mg BID; Level 50-100",route:"IV, PO",indication:"Generalized epilepsy, absence seizures, bipolar, migraine ppx",pearls:"Broad-spectrum AED. Highly teratogenic — AVOID in women of childbearing potential. ↑LFTs, thrombocytopenia. Hyperammonemia without liver failure. Weight gain",se:"Hepatotoxicity, pancreatitis, teratogenicity, thrombocytopenia, weight gain, tremor, alopecia",tags:["second-line"]},
    {name:"Lamotrigine (Lamictal)",moa:"Na+ channel blocker + glutamate modulator",dose:"Start 25mg daily (50 with enzyme inducer); titrate slowly over 6-8wk",route:"PO",indication:"Focal/generalized epilepsy, bipolar maintenance, Lennox-Gastaut",pearls:"MUST titrate slowly (SJS/TEN risk — especially with rapid titration or valproate co-admin). Weight-neutral. Safe in pregnancy (preferred AED). Valproate doubles lamotrigine levels (halve dose). No blood monitoring needed",se:"SJS/TEN (titrate slowly!), headache, dizziness, nausea, blurred vision",tags:["first-line"]},
    {name:"Fosphenytoin / Phenytoin",moa:"Na+ channel blocker",dose:"Load 20 PE/kg IV (fosphenytoin at 150 PE/min)",route:"IV",indication:"SE (2nd-line), seizure ppx",pearls:"Monitor cardiac rhythm during load. Free phenytoin level (1-2 mcg/mL). Zero-order kinetics. Massive drug interactions (CYP inducer). Avoid in absence seizures",se:"Hypotension/arrhythmia, gingival hyperplasia, SJS/TEN, cerebellar atrophy",tags:["first-line"]}
  ],
  "Stroke":[
    {name:"Alteplase (tPA) / Tenecteplase",moa:"tPA → fibrinolysis",dose:"Alteplase 0.9mg/kg (max 90mg): 10% bolus, 90% over 60min; Tenecteplase 0.25mg/kg bolus",route:"IV",indication:"Acute ischemic stroke ≤4.5h; LVO pre-thrombectomy (tenecteplase)",pearls:"Door-to-needle <60min. BP <185/110 before, <180/105 after. Tenecteplase single bolus for LVO (AcT trial). WAKE-UP trial: MRI-guided tPA for wake-up strokes",se:"ICH 6%, angioedema (ACEi patients), systemic bleeding",tags:["first-line"]}
  ],
  "Neuropathic Pain":[
    {name:"Gabapentin (Neurontin) / Pregabalin (Lyrica)",moa:"α2δ Ca2+ channel ligand → ↓excitatory neurotransmitter release",dose:"Gabapentin: start 100-300mg TID, max 3600mg/day; Pregabalin: 50-150mg BID",route:"PO",indication:"Neuropathic pain, postherpetic neuralgia, fibromyalgia (pregabalin), seizures (adjunct)",pearls:"Gabapentin: TID dosing, renal adjustment, non-linear absorption (ceiling effect). Pregabalin: BID, linear pharmacokinetics, Schedule V. Both cause sedation/dizziness — start low. Abuse potential (pregabalin > gabapentin)",se:"Sedation, dizziness, peripheral edema, weight gain, respiratory depression (with opioids)",tags:["first-line"]},
    {name:"Duloxetine (Cymbalta)",moa:"SNRI → serotonin + norepinephrine reuptake inhibition",dose:"30mg daily → 60mg daily",route:"PO",indication:"Neuropathic pain (diabetic), fibromyalgia, depression, anxiety, chronic MSK pain",pearls:"Dual indication: pain + depression. Do NOT crush/chew (enteric coated). Discontinuation syndrome (taper slowly). Avoid in severe liver disease. Also useful for stress urinary incontinence",se:"Nausea, dry mouth, constipation, dizziness, insomnia, serotonin syndrome (with other serotonergics)",tags:["first-line"]}
  ]
},
"Hematology":{
  "Anticoagulation Reversal":[
    {name:"4F-PCC (Kcentra) / Idarucizumab (Praxbind) / Andexanet (Andexxa) / Protamine / Vitamin K",moa:"See ICU section for detailed entries",dose:"See detailed entries",route:"IV",indication:"Urgent reversal of warfarin/DOACs/heparin",pearls:"Kcentra: warfarin (+ vit K). Idarucizumab: dabigatran only. Andexanet: Xa inhibitors (expensive). Protamine: heparin. See ICU section for complete details",se:"Thrombosis risk with all reversal agents",tags:["first-line"]}
  ],
  "Hematologic Therapies":[
    {name:"Filgrastim (Neupogen) / Pegfilgrastim (Neulasta)",moa:"G-CSF → stimulates neutrophil production",dose:"Filgrastim 5-10 mcg/kg SC daily; Pegfilgrastim 6mg SC × 1",route:"SC",indication:"Chemo-induced neutropenia prophylaxis, febrile neutropenia adjunct, stem cell mobilization",pearls:"Give 24-72h AFTER chemo (not same day). Pegfilgrastim: single dose per cycle. Bone pain common (tx: NSAID/loratadine). Avoid in AML. D/C when ANC >10K",se:"Bone pain, splenic rupture (rare), ARDS (rare), leukocytosis",tags:["first-line"]},
    {name:"IV Iron (Ferric Carboxymaltose/Iron Sucrose/Ferumoxytol)",moa:"Parenteral iron replacement",dose:"Ferric carboxymaltose 750mg IV ×2 (1wk apart); Iron sucrose 200-300mg IV",route:"IV",indication:"Iron deficiency anemia (oral intolerant, CKD, IBD, HF, malabsorption)",pearls:"IV iron now preferred in many settings (CKD, HF, IBD). AFFIRM-AHF: ferric carboxymaltose ↓HF hospitalization. Ferric carboxymaltose can cause HYPOphosphatemia (FGF23-mediated). Infusion reactions possible — test dose not required for most formulations",se:"Hypophosphatemia (ferric carboxymaltose), infusion reactions, hypotension, constipation, dark stool",tags:["first-line"]},
    {name:"Packed RBCs / Platelets / FFP / Cryoprecipitate",moa:"Blood product replacement",dose:"See ICU section for detailed transfusion triggers",route:"IV",indication:"Anemia (Hgb<7 general, <8 cardiac), thrombocytopenia, coagulopathy, hypofibrinogenemia",pearls:"Restrictive strategy non-inferior (TRICC/FOCUS). MTP 1:1:1. Cryo for fibrinogen <100-150 (or DIC). See ICU section for details",se:"TACO, TRALI, hemolytic, febrile, allergic reactions",tags:["first-line"]}
  ]
},
"Rheumatology":{
  "NSAIDs & Gout":[
    {name:"NSAIDs (Ibuprofen/Naproxen/Indomethacin/Celecoxib/Diclofenac)",moa:"COX-1/2 inhibitors",dose:"See earlier entries",route:"PO, topical (diclofenac)",indication:"OA, RA, gout, inflammation, pain",pearls:"Naproxen: lowest CV risk. Indomethacin: most potent for gout. Celecoxib: less GI. Topical diclofenac: OA with less systemic risk. All: avoid CKD/HF/GI bleed risk",se:"GI bleeding, AKI, CV events, fluid retention, HTN",tags:["first-line"]},
    {name:"Colchicine / Allopurinol / Febuxostat",moa:"See earlier entries",dose:"See earlier entries",route:"PO",indication:"Gout acute (colchicine) / chronic (allopurinol, febuxostat)",pearls:"See earlier entries. HLA-B*5801 testing before allopurinol. Don't start ULT during acute flare. Colchicine: pericarditis too",se:"See earlier entries",tags:["first-line"]}
  ],
  "Corticosteroids":[
    {name:"Prednisone / Methylprednisolone",moa:"Glucocorticoid — broad anti-inflammatory/immunosuppressive",dose:"Low: 5-10mg; Moderate: 0.5mg/kg; High: 1mg/kg; Pulse: methylpred 1g IV ×3d",route:"PO, IV",indication:"Autoimmune flares, vasculitis, myositis, SLE, PMR/GCA, severe asthma/COPD",pearls:"GCA: start 40-60mg IMMEDIATELY (don't wait for biopsy). SLE nephritis: pulse methylpred → maintenance. Taper slowly after prolonged use (adrenal suppression). PJP ppx if prednisone ≥20mg ×4wk",se:"Hyperglycemia, infection, osteoporosis, AVN, cataracts, HTN, adrenal suppression, psychosis, weight gain, skin thinning",tags:["first-line"]}
  ],
  "DMARDs (Conventional)":[
    {name:"Methotrexate / Hydroxychloroquine / Sulfasalazine / Leflunomide",moa:"Various immunomodulatory mechanisms",dose:"See earlier entries",route:"PO, SC (MTX)",indication:"RA, SLE (HCQ), PsA, vasculitis maintenance",pearls:"MTX: 1st-line DMARD for RA. Weekly dosing (daily=fatal error). Always add folate. HCQ: cornerstone of SLE. Annual retinal exam. Sulfasalazine: RA/SpA, check G6PD. Leflunomide: alt to MTX in RA, teratogenic",se:"See earlier entries for each agent",tags:["first-line"]}
  ],
  "Biologic DMARDs":[
    {name:"TNF Inhibitors (Infliximab/Adalimumab/Etanercept/Certolizumab/Golimumab)",moa:"Anti-TNF-α → ↓inflammatory cascade",dose:"Various SC/IV regimens",route:"SC, IV",indication:"RA, PsA, AS, IBD (infliximab/adalimumab), psoriasis",pearls:"Screen for TB + HBV before starting. Check drug levels if loss of response. ↑Infection risk. Avoid live vaccines. CI: active infection, HF (NYHA III-IV), demyelinating disease",se:"Infections (TB, opportunistic), infusion/injection reactions, demyelination, lupus-like syndrome, HF worsening",tags:["first-line"]},
    {name:"IL-6 Inhibitors (Tocilizumab/Sarilumab)",moa:"IL-6 receptor blockade",dose:"Tocilizumab 4-8mg/kg IV q4wk or 162mg SC weekly",route:"IV, SC",indication:"RA (moderate-severe), GCA (steroid-sparing), CRS (CAR-T complications)",pearls:"Suppresses CRP/ESR (cannot use as inflammatory markers on therapy). Monitor LFTs, lipids. ↑GI perforation risk (diverticular disease). FDA-approved for GCA and CRS (cytokine release syndrome from CAR-T)",se:"Infections, hepatotoxicity, hyperlipidemia, GI perforation, neutropenia",tags:["first-line"]},
    {name:"JAK Inhibitors (Tofacitinib/Baricitinib/Upadacitinib)",moa:"Janus kinase (JAK) inhibitors → ↓cytokine signaling",dose:"Tofacitinib 5mg BID; Baricitinib 2mg daily; Upadacitinib 15mg daily",route:"PO",indication:"RA (moderate-severe after anti-TNF failure), UC (tofacitinib), AD (upadacitinib)",pearls:"Oral small molecules (vs injectable biologics). ORAL Surveillance trial: tofacitinib ↑CV events and malignancy vs anti-TNF in RA >50 with CV risk. FDA box warning for all JAKi. Screen for TB/HBV. VTE risk. Herpes zoster risk (consider Shingrix vaccine before starting)",se:"Infections (herpes zoster), VTE, MACE, malignancy (box warning), hyperlipidemia, cytopenias",tags:["second-line"]},
    {name:"Rituximab (Rituxan)",moa:"Anti-CD20 → B-cell depletion",dose:"1000mg IV ×2 doses (2wk apart); repeat q6mo",route:"IV",indication:"RA (anti-TNF failure), ANCA vasculitis (induction + maintenance), SLE nephritis, pemphigus",pearls:"B-cell depletion lasts 6-12 months. Screen HBV (reactivation risk). Check immunoglobulin levels. PML risk (rare). Infusion reactions (premedicate). RAVE trial: rituximab non-inferior to cyclophosphamide for ANCA vasculitis",se:"Infusion reactions, infections, HBV reactivation, PML (rare), hypogammaglobulinemia",tags:["first-line"]}
  ]
},
"Psychiatry":{
  "Alcohol/Substance Withdrawal":[
    {name:"Benzodiazepines (Lorazepam/Diazepam/Chlordiazepoxide)",moa:"GABA-A modulators",dose:"Symptom-triggered (CIWA): lorazepam 1-4mg IV/PO q1h PRN CIWA≥8-10",route:"IV, PO",indication:"Alcohol withdrawal (1st-line), seizure prevention",pearls:"CIWA-guided > fixed schedule. Lorazepam: preferred in liver failure (no hepatic oxidation). Diazepam: faster onset, longer acting. Chlordiazepoxide: mild inpatient withdrawal (PO). ALWAYS thiamine 500mg IV TID BEFORE glucose",se:"Respiratory depression, oversedation, paradoxical agitation",tags:["first-line"]},
    {name:"Phenobarbital",moa:"Barbiturate — direct GABA-A agonist",dose:"Benzo-refractory: 130-260mg IV q15-30min; Load 10mg/kg",route:"IV, PO",indication:"Benzo-refractory alcohol withdrawal, adjunct severe withdrawal",pearls:"Works when benzos fail (directly opens GABA-A — doesn't need endogenous GABA). Very long t½ (2-6 days). ICU monitoring required",se:"Respiratory depression, hypotension, oversedation (long t½)",tags:["second-line"]}
  ],
  "Antipsychotics & Agitation":[
    {name:"Haloperidol (Haldol)",moa:"D2 antagonist (typical antipsychotic)",dose:"Agitation 2-5mg IV/IM q30-60min; ICU delirium 0.5-2mg IV BID",route:"IV, IM, PO",indication:"Acute agitation, psychosis, hyperactive delirium",pearls:"QTc — get baseline ECG, hold QTc>500. EPS more with IM/PO. Tx dystonia: diphenhydramine. Avoid in Parkinson/Lewy body. MIND-USA: did not ↓delirium in ICU",se:"QT prolongation, EPS, NMS, tardive dyskinesia",tags:["first-line"]},
    {name:"Quetiapine (Seroquel)",moa:"Atypical — D2/5-HT2A/H1/α1 antagonist",dose:"Delirium 12.5-50mg q6-12h; Psychosis 25-800mg daily",route:"PO only",indication:"ICU delirium (PO), psychosis, bipolar, insomnia (off-label)",pearls:"Most sedating atypical. Less EPS than haloperidol. Start low in elderly. Metabolic SEs: weight gain, hyperglycemia",se:"Sedation, orthostatic hypotension, QT, metabolic syndrome, weight gain",tags:["first-line"]}
  ],
  "Palliative Care":[
    {name:"Opioids for Dyspnea (Morphine/Hydromorphone at low doses)",moa:"μ-opioid → ↓respiratory drive perception, ↓dyspnea",dose:"Morphine 1-2mg IV q4h or 5-10mg PO q4h; hydromorphone 0.2-0.4mg IV",route:"IV, PO, SC, nebulized",indication:"Refractory dyspnea in advanced disease, pain management in palliative care",pearls:"Low-dose opioids ↓dyspnea perception without significant respiratory depression. Morphine: useful for dyspnea in palliative care. Start low in opioid-naive. Benzodiazepines can supplement for anxiety component of dyspnea. Nebulized opioids: limited evidence but used in practice",se:"Sedation, respiratory depression (dose-dependent), constipation, nausea",tags:["first-line"]}
  ]
}
};
